### ISSUE TITLE
Reading .sbx files with GUI

### ISSUE THREAD

**Issue by kirstyngrams** [MouseLand/suite2p#1037]
Hello, I am trying to use the GUI to process and analyze scanbox files. When I use the GUI (after changing the input to sbx) I get the following long list of errors. This occurs when I am loading just one file as well. I have version 0.14.2. Thanks!

```
{'data_path': ['[Y:/nar/nar032/nar032d](http://y/nar/nar032/nar032d)'], 'subfolders': [], 'h5py_key': 'data', 'save_path0': '[Y:/nar/nar032/nar032d](http://y/nar/nar032/nar032d)', 'fast_disk': '[Y:/nar/nar032/nar032d](http://y/nar/nar032/nar032d)', 'input_format': 'sbx'}
sbx
** Found 4 sbx - converting to binary **
Scanbox files:
Y:/nar/nar032/nar032d\nar032d__001.sbx
Y:/nar/nar032/nar032d\nar032d__002.sbx
Y:/nar/nar032/nar032d\nar032d__003.sbx
Y:/nar/nar032/nar032d\nar032d__004.sbx
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\runpy.py", line 197, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 84, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 77, in main
    run_s2p(ops, db)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 472, in run_s2p
>>>ERROR<<<
    ops0 = convert_funs[ops["input_format"]](ops.copy())
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\sbx.py", line 52, in sbx_to_binary
    tmpsbx = sbx_memmap(sbxlist[0])
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\sbxreader\reader.py", line 130, in __new__
    sbx_metadata = sbx_get_metadata(filename)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\sbxreader\reader.py", line 30, in sbx_get_metadata
    info = sbx_get_info(sbxfilename)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\sbxreader\reader.py", line 20, in sbx_get_info
    info = loadmat(matfile,squeeze_me=True,struct_as_record=False)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\_mio.py", line 226, in loadmat
>>>ERROR<<<
    MR, _ = mat_reader_factory(f, **kwargs)
  File "C:\Users\smelluser\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\_mio.py", line 80, in mat_reader_factory
    raise NotImplementedError('Please use HDF reader for matlab v7.3 '
NotImplementedError: Please use HDF reader for matlab v7.3 files, e.g. h5py
Interrupted by error (not finished)
```

**Comment by chriski777** [comment]
Hi @kirstyngrams, sorry for the late reply. What version of suite2p and Scipy are you using?

**Comment by chriski777** [comment]
Closing due to inactivity. Feel free to reopen if the issue persists @kirstyngrams!
