### ISSUE TITLE
BUG: Gives me the following error when I try to run a tiff file on suite2p

### ISSUE THREAD

**Issue by kyesther00** [MouseLand/suite2p#1040]
### Describe the issue:

Every time I run suite2p, it goes through the registration process that takes a few minutes and then gives me the following error.

### Reproduce the code example:

```python
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 429, in run_s2p
>>>ERROR<<<
    op = run_plane(op, ops_path=ops_path)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 292, in run_plane
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 131, in pipeline
    classfile=classfile)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 152, in detection_wrapper
    classfile=classfile,
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 211, in select_rois
    percentile=ops.get('active_percentile', 0.0),
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 307, in sparsery
>>>ERROR<<<
    scale, estimate_mode = find_best_scale(I=I, spatial_scale=spatial_scale)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 266, in find_best_scale
    scale = estimate_spatial_scale(I=I)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\sparsedetect.py", line 256, in estimate_spatial_scale
    im, _ = mode(imap[ipk][isort[:50]], keepdims=True)
```

### Error message:

```shell
TypeError: mode() got an unexpected keyword argument 'keepdims'
Interrupted by error (not finished)
```

### Version information:

suite2p v0.11.1

**Comment by ryanirl** [comment]
To fix this, your likely going to want to update scipy such that `scipy>=1.9.0` as the keepdims argument was added in 1.9.0 (as listed [here](https://docs.scipy.org/doc/scipy/release/1.9.0-notes.html)). Do note that a [commit was made](https://github.com/MouseLand/suite2p/commit/e184c21f203be1e7e64668b30a46b3aa2b59a076) to suite2p in v0.14.2 to fix this. Also, to ensure compatibility with Python and NumPy versions, I would consult [this scipy reference](https://docs.scipy.org/doc/scipy/dev/toolchain.html) before updating.

**Comment by chriski777** [comment]
Hi @kyesther00, as @ryanirl mentioned, this is an issue that was patched in the latest version of suite2p. Could you try running suite2p again after updating to the latest version (v0.14.2)? I'll close this for now but feel free to reopen if the issue persists.

**Comment by ayelettg** [comment]
I begin with an x number of tiff files and after registration in suite2p I miss a small number... why does the total amount of tiff files change after registration?
