### ISSUE TITLE
BUG: current version of Suite2p puts default ops and classifiers in Windows 10 Users folder but doesn't account for spaces in path

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#1066]
### Describe the issue:

can you please add a way to either put these folders somewhere else, or add quotes or whatever to make the full path literal so that spaces and other escape characters will be included as literal strings in the pathname?

i really don't want to have to change my Windows User name on this university computer etc and i have lots of other stuff there already

thanks,

evan

### Reproduce the code example:

```python
for some reason this works to load suite2p and look and data, but not to do new runs:

python -u -W ignore -m suite2p --ops C:\Users\McCormick Lab\.suite2p\ops\ops.npy --db C:\Users\McCormick Lab\.suite2p\ops\db.npy

with new runs, the space in the path name results in: Lab\.suite2p...etc being taken as the intended path, and it crashes

thanks,

evan
```

### Error message:

```shell
python -u -W ignore -m suite2p --ops C:\Users\McCormick Lab\.suite2p\ops\ops.npy --db C:\Users\McCormick Lab\.suite2p\ops\db.npy

with new runs, the space in the path name results in: Lab\.suite2p...etc being taken as the intended path, and it crashes

thanks,

evan
```

### Version information:

suite2p v0.14.3

but also other recent versions

### Context for the issue:

with new runs, the space in the path name results in: Lab\.suite2p...etc being taken as the intended path, and it crashes

thanks,

evan

**Comment by carsen-stringer** [comment]
Sorry I thought we had fixed this issue Evan. If you run `python -u -W ignore -m suite2p --ops "C:\Users\McCormick Lab\.suite2p\ops\ops.npy" --db "C:\Users\McCormick Lab\.suite2p\ops\db.npy"` do you receive any errors? If not then it's just a matter of changing how the GUI calls this command in rungui.py

**Comment by vickerse1** [comment]
running that line works, w/ no error

which line in rungui.py should i change, what does it currently say, and what should i change it to?

thanks,

evan
________________________________

**Comment by carsen-stringer** [comment]
Ah great, this line here: https://github.com/MouseLand/suite2p/blob/3fb28671c860daa7a72b444cecd8962ee84661fd/suite2p/gui/rungui.py#L451C49-L451C49

If you can try changing it to:
`cmd = f'-u -W ignore -m suite2p --ops "{ops_file}" --db "{db_file}"'`

If it works we can change it or you can make a pull request with the change, thanks!

**Comment by vickerse1** [comment]
i made that change and now i get this error:

----
(suite2p) C:\WINDOWS\system32>python -m suite2p
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\suite2p_git\suite2p\suite2p\__main__.py", line 84, in <module>
    main()
  File "c:\suite2p_git\suite2p\suite2p\__main__.py", line 79, in main
    from suite2p import gui
  File "c:\suite2p_git\suite2p\suite2p\gui\__init__.py", line 4, in <module>
    from .gui2p import run
  File "c:\suite2p_git\suite2p\suite2p\gui\gui2p.py", line 11, in <module>
    from . import menus, io, merge, views, buttons, classgui, traces, graphics, masks
  File "c:\suite2p_git\suite2p\suite2p\gui\menus.py", line 8, in <module>
    from . import reggui, drawroi, merge, io, rungui, visualize, classgui
  File "c:\suite2p_git\suite2p\suite2p\gui\rungui.py", line 451
    cmd = f'-u -W ignore -m suite2p --ops "{ops_file}" --db "{db_file}"'
TabError: inconsistent use of tabs and spaces in indentation
-------------

this is what lines 449-453  in my rungui.py look like:


 print(self.db)
    print("Running suite2p with command:")
cmd = f'-u -W ignore -m suite2p --ops "{ops_file}" --db "{db_file}"'
        #cmd = f"-u -W ignore -m suite2p --ops {ops_file} --db {db_file}"
        print("python " + cmd)


thanks,

evan
________________________________

**Comment by vickerse1** [comment]
Hi,

Do we have any new insights on this issue yet?

Thanks,

Evan
________________________________

**Comment by vickerse1** [comment]
Hi,

I created a new Windows admin user account with no space in the name and installed in C:/ while logged in to that account, and I still have the problem.

It's strange that the .suite2p folder w/ ops keeps going in my "McCormick Lab" folder, even though that is not the user folder corresponding to the active admin account. Could it be that that's where python is installed or some other weird path issue I don't understand?

Thanks,

Evan
________________________________

**Comment by vickerse1** [comment]
Hi,

I uninstalled my developer version and re-installed w/ the regular install again, and I still have the same problem.

I just need to know why it's putting the .suite2p folder in the McCormick Lab folder. It would be nice if I could put this in a different admin user folder somehow.

Thanks,

Evan
________________________________

**Comment by chriski777** [comment]
Hi @vickerse1, hopefully, the comment I added in #1064 explains why you're getting the error related to the tabs. Carsen's suggestion on editing the rungui.py won't entirely fix the issue on the Windows machine (at least when tested on mine) because the `ops_file`  and `db_file`  in the `run_s2p` function of `rungui.py` are still not properly set to include the space and all the characters that come after. 

Just wondering though, does Carsen's suggestion of including double quotes around the pathnames (ie, `python -u -W ignore -m suite2p --ops "C:\Users\McCormick Lab\.suite2p\ops\ops.npy" --db "C:\Users\McCormick Lab\.suite2p\ops\db.npy"`) not solve this problem? For apps that run on Windows, it's common to specify double quotes to work with spaces in pathnames. Implementing this fix may also cause issues on Linux machines that use different escape characters to include spaces.

**Comment by vickerse1** [comment]
As far as I remember that didn't work.

What's the line # of the other location in the code I need to make the change?

Also, what exact code do I need to put there?

Thanks,

Evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by chriski777** [comment]
Hey @vickerse1, I'm responding to your comment here just to keep everything consolidated in one thread: 

_"Yes I'm sure then that I just copy pasted this command and still got the indentation and spaces error when I try to start a new run.
I will try again I guess, but I don't know why this would be an issue from the command line. It makes sense that it might be an issue when changing the .py file."_

I think this suggests that you ran the command mentioned above AFTER an edit had been made to rungui.py and the suite2p developer version was installed. 

I'd suggest the following approach to remedy this:
1. Uninstall suite2p : `pip uninstall suite2p`
2. Re-installing the regular version: `pip install suite2p`
3. Then just run ```python -u -W ignore -m suite2p --ops "C:\Users\McCormick Lab\.suite2p\ops\ops.npy" --db "C:\Users\McCormick Lab\.suite2p\ops\db.npy"``` in the command line.  

No lines of code need to be changed here and it should work (seems it worked for you too based on the third comment of this thread?). I've also tested this on my windows machine and this works for pathnames with spaces.

**Comment by vickerse1** [comment]
Hi Chris,

OK great I'll try that.

Thanks,

Evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vickerse1** [comment]
I still think, though, that the result will be that suite2p opens and i can load data, but i cannot do new runs from the gui without the same error recurring.

-evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vickerse1** [comment]
Hi Chris,

Yes OK great that runs from the command line.

However, I want to run suite2p in the GUI.

What should I do?

Thanks,

Evan
________________________________

**Comment by vickerse1** [comment]
Hi Chris,

I modified the line that Carsen suggested in rungui.py, this time making sure to use all spaces, as the other lines used.

Now, I don't get the indentation error.

However, some other line in the code still appears to be calling the wrong path, unquoted w/ the space.

Before you mentioned something about another location in run_s2p.py that needs to be modified.

Could you please tell me where this is?

Thanks,

Evan
________________________________

**Comment by vickerse1** [comment]
how do I fix the issue that "because the ops_file and db_file in the run_s2p function of rungui.py are still not properly set to include the space and all the characters that come after."

?

Thanks,

Evan

________________________________

**Comment by chriski777** [comment]
You can run the gui from the command line using `suite2p`. Then, go to `File > Load processed data` and put the `stat.npy` of your processed data. 

I don't know how to make that change yet and wouldn't necessarily call it something to fix as it can complicate suite2p's usage with Linux/Mac OS machines. I'd recommend not changing that portion of the code. Even if this change was made, I believe you'd still have to run the `suite2p` command and load the processed data to look at the output

**Comment by vickerse1** [comment]
yes loading data into the gui already works without this fix

can you please fix this issue so I can do windows runs from the gui?

couldn't there just be a separate windows version? it's a very common operating system

i still don't understand why this worked in previous versions but doesn't work now

before i would always just run everything in the gui and it would load directly after processing. this still works in linux, and it works in windows but unfortunately not when there's a space in the path name

I can't change the pathname because i have a lot of other stuff there and i think it would be a disaster

thanks

evan
________________________________

**Comment by chriski777** [comment]
Ah... Sorry, I misunderstood what you were saying earlier. I did not know you were trying to get things running on the GUI side of things and thought you were just trying to get the `python -u -W ignore -m suite2p --ops C:\Users\McCormick Lab\.suite2p\ops\ops.npy --db C:\Users\McCormick Lab\.suite2p\ops\db.npy
` command to work. 

I can now reproduce the GUI error you're talking about and will try to debug this.

**Comment by vickerse1** [comment]
Hi Chris,

OK, cool - thanks. Sorry I wasn't more clear initially.

In the meantime, I've deleted my current Windows version and installed a gui version in WSL (windows subsystem for linux).

Everything works, but when I run "python -m suite2p", I get the following error and the gui does not open:

-------
Traceback (most recent call last):
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 84, in <module>
    main()
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 79, in main
    from suite2p import gui
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/__init__.py", line 4, in <module>
    from .gui2p import run
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/gui2p.py", line 7, in <module>
    import pyqtgraph as pg
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 182, in <module>
    import PyQt6.QtGui
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
-----------

Should I file a separate github issue for this?

I installed suite2p with the following command:

python -m pip install suite2p[gui]

Should I have installed the developer version instead?

Thanks,

Evan


________________________________

**Comment by chriski777** [comment]
Hi @vickerse1, sorry but I am unable to reproduce your GUI error. It turns out that changing rungui.py to have 
`cmd = f'-u -W ignore -m suite2p --ops "{ops_file}" --db "{db_file}"'` was the reason on my end. 

"It's strange that the .suite2p folder w/ ops keeps going in my "McCormick Lab" folder, even though that is not the user folder corresponding to the active admin account. Could it be that that's where python is installed or some other weird path issue I don't understand?"

Referring back to this, suite2p defaults to your home directory which on Windows is determined by your USERPROFILE environment variable. You can check what yours is set to by calling 
```echo %USERPROFILE%``` on your command line when logged into your active admin account. You'll have to change this on your other account (the one without spaces). Then, I believe the GUI should work normally.

**Comment by vickerse1** [comment]
Ok. How do I change it?

Thanks,

Evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vickerse1** [comment]
Hi Chris,

Is there a way have suite2p ask the user which folder they want to use, instead of defaulting to the home directory?

I think this would be a good work around. Maybe it's a feature request though?

Thanks,

Evan

Sent from my T-Mobile 5G Device
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vickerse1** [comment]
Hi Chris,

OK, which of these environment variables to I need to change (see attached image)?

OneDrive? Path? TEMP? TMP?

Which one is "home"?


Thanks,

Evan
________________________________

**Comment by chriski777** [comment]
Closing this as the conversation thread moved over to #1070.
