### ISSUE TITLE
BUG: GUI doesn't load in suite2p installed in WSL, Import Error: libEGL.so.1, no such file or directory

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#1070]
### Describe the issue:

I installed a gui version of suite2p in WSL (windows subsystem for linux).

Everything works, but when I run "python -m suite2p", I get the following error and the gui does not open:

-------
Traceback (most recent call last):
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 84, in <module>
    main()
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 79, in main
    from suite2p import gui
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/__init__.py", line 4, in <module>
    from .gui2p import run
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/gui2p.py", line 7, in <module>
    import pyqtgraph as pg
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 182, in <module>
    import PyQt6.QtGui
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
-----------

Should I file a separate github issue for this?

I installed suite2p with the following command:

python -m pip install suite2p[gui]

Should I have installed the developer version instead?

### Reproduce the code example:

```python
python -m suite2p
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 84, in <module>
    main()
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 79, in main
    from suite2p import gui
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/__init__.py", line 4, in <module>
    from .gui2p import run
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/gui2p.py", line 7, in <module>
    import pyqtgraph as pg
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 182, in <module>
    import PyQt6.QtGui
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
```

### Version information:

Suite2p v0.14.3 Linux (WSL) in Ubuntu 20.04.4 LTS

### Context for the issue:

Windows 10. Can't do runs in GUI in Windows because default ops and dbs are in an unchangeable user folder with a space in the name.

so, as a workaround i tried installing in windows subsystem for linux (WSL). however, here the gui doesn't work at all. should it? do I need to install a different version of PyQt6? It seems to be missing libEGL.so.1....do I need a different version of this for linux?

thanks,

evan

**Comment by chriski777** [comment]
Can you try running `apt-get update && apt-get install libgl1`?

**Comment by vickerse1** [comment]
Hi,

It seems that that almost worked, but one or two of the repositories couldn't be accessed (?):

-------------
(suite2p) ***@***.***:/mnt/c/suite2p_git_linux/suite2p$ sudo apt-get update && apt-get install libgl1
[sudo] password for vickerse:
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease [1581 B]
Err:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Ign:3 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu focal InRelease
Hit:4 http://archive.ubuntu.com/ubuntu focal InRelease
Err:5 http://ppa.launchpad.net/mc3man/trusty-media/ubuntu focal Release
  404  Not Found [IP: 185.125.190.80 80]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:7 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2636 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [3020 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [405 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/main amd64 c-n-f Metadata [13.2 kB]
Get:12 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2448 kB]
Get:13 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [342 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 c-n-f Metadata [552 B]
Get:15 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [915 kB]
Get:16 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [192 kB]
Get:17 http://security.ubuntu.com/ubuntu focal-security/universe amd64 c-n-f Metadata [19.2 kB]
Get:18 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [23.6 kB]
Get:19 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [5504 B]
Get:20 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 c-n-f Metadata [548 B]
Get:21 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [488 kB]
Get:22 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 c-n-f Metadata [17.2 kB]
Get:23 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [2569 kB]
Get:24 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [359 kB]
Get:25 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 c-n-f Metadata [552 B]
Get:26 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [1140 kB]
Get:27 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [273 kB]
Get:28 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 c-n-f Metadata [25.7 kB]
Get:29 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [25.8 kB]
Get:30 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [7484 B]
Get:31 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 c-n-f Metadata [620 B]
Get:32 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 Packages [45.7 kB]
Get:33 http://archive.ubuntu.com/ubuntu focal-backports/main amd64 c-n-f Metadata [1420 B]
Get:34 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [25.0 kB]
Get:35 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 c-n-f Metadata [880 B]
Reading package lists... Done
W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://ppa.launchpad.net/mc3man/trusty-media/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
-----------------

then, when I run python -m suite2p I get this:
--------
(suite2p) ***@***.***:/mnt/c/suite2p_git_linux/suite2p$ python -m suite2p
Traceback (most recent call last):
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 84, in <module>
    main()
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/__main__.py", line 79, in main
    from suite2p import gui
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/__init__.py", line 4, in <module>
    from .gui2p import run
  File "/mnt/c/suite2p_git_linux/suite2p/suite2p/gui/gui2p.py", line 7, in <module>
    import pyqtgraph as pg
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 182, in <module>
    import PyQt6.QtGui
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
----------------------

Do you have any ideas about what to do next?

Thanks,

Evan
________________________________

**Comment by chriski777** [comment]
What about `apt-get update && apt-get install libgl1 --allow-unauthenticated`?

**Comment by vickerse1** [comment]
Hi Chris,

I tried this and received the following errors:

-----------------
(suite2p) ***@***.***:~$ apt-get update && apt-get install libgl1 --allow-unauthenticated
Reading package lists... Done
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)
------------------------

....then, when trying to run gui:

-----------
(suite2p) ***@***.***:~$ python -m suite2p
Traceback (most recent call last):
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/__main__.py", line 84, in <module>
    main()
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/__main__.py", line 79, in main
    from suite2p import gui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/gui/__init__.py", line 4, in <module>
    from .gui2p import run
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/gui/gui2p.py", line 7, in <module>
    import pyqtgraph as pg
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/__init__.py", line 18, in <module>
    from .colors import palette
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/colors/palette.py", line 1, in <module>
    from ..Qt import QtGui
  File "/home/vickerse/anaconda3/envs/suite2p/lib/python3.9/site-packages/pyqtgraph/Qt/__init__.py", line 182, in <module>
    import PyQt6.QtGui
ImportError: libEGL.so.1: cannot open shared object file: No such file or directory
-------------

Any suggestions? I still cannot run the Suite2p gui either in WSL or Windows w/ user folder containing space in name on my local computer, and I see no safe way of fixing the user folder name issue (i.e. w/o changing the registry, which is apparently unstable?).



Thanks,

Evan
________________________________

**Comment by chriski777** [comment]
Can you try running the commands with sudo attached to the front (ie, `sudo apt-get update && apt-get install libgl1 --allow-unauthenticated`)? Then, try running `apt-get update && apt-get install libgl1`.

**Comment by chriski777** [comment]
Closing due to inactivity, @vickerse1, feel free to reopen if the issue persists.
