### ISSUE TITLE
BUG: creating combined view gives rise to error when ignore_flyback>0

### ISSUE THREAD

**Issue by just-meng** [MouseLand/suite2p#1082]
### Describe the issue:

Related to #1081. Rerunning suite2p on multiplane data where previously `ignore_flyback=2` was set gives rise to an error that I believe occurs only because it is not taken into account that plane2 has to be ignored again. 

### Reproduce the code example:

```python
The easiest way to reproduce is to run suite2p on multiplane data and set `ignore_flyback>1` and `combined=1`. And simply run it another time.
```

### Error message:

```shell
{'data_path': ['01_data/01_raw_data/02_Psychedelics_L5b_2p/231113D_Sim-Cre/2023-12-19_Saline/Saline_0', '01_data/01_raw_data/02_Psychedelics_L5b_2p/231113D_Sim-Cre/2023-12-19_Saline/Saline_0.9', '01_data/01_raw_data/02_Psychedelics_L5b_2p/231113D_Sim-Cre/2023-12-20_LSD/LSD_0', '01_data/01_raw_data/02_Psychedelics_L5b_2p/231113D_Sim-Cre/2023-12-20_LSD/LSD_0.4'], 'save_path0': '01_data/02_preprocessed_data/02_Psychedelics_L5b_suite2p/231113D_Sim-Cre/Saline_LSD', 'fast_disk': '/home/meng/Fast_disk/231113D_Sim-Cre/Saline_LSD'}
tif
** Found 468 tifs - converting to binary **
3600 frames of binary, time 16.63 sec.
7200 frames of binary, time 33.88 sec.
10800 frames of binary, time 51.08 sec.
14400 frames of binary, time 69.57 sec.
18000 frames of binary, time 97.42 sec.
21600 frames of binary, time 125.81 sec.
25200 frames of binary, time 153.15 sec.
28800 frames of binary, time 180.92 sec.
32400 frames of binary, time 208.34 sec.
36000 frames of binary, time 234.75 sec.
39600 frames of binary, time 260.59 sec.
43200 frames of binary, time 287.77 sec.
46800 frames of binary, time 314.89 sec.
50400 frames of binary, time 343.38 sec.
54000 frames of binary, time 370.69 sec.
57600 frames of binary, time 398.88 sec.
61200 frames of binary, time 426.36 sec.
64800 frames of binary, time 456.49 sec.
68400 frames of binary, time 484.39 sec.
72000 frames of binary, time 512.72 sec.
75600 frames of binary, time 540.16 sec.
79200 frames of binary, time 568.12 sec.
82800 frames of binary, time 596.18 sec.
86400 frames of binary, time 623.65 sec.
90000 frames of binary, time 651.55 sec.
93600 frames of binary, time 679.71 sec.
97200 frames of binary, time 707.78 sec.
100800 frames of binary, time 726.51 sec.
104400 frames of binary, time 743.08 sec.
108000 frames of binary, time 760.31 sec.
111600 frames of binary, time 777.21 sec.
115200 frames of binary, time 794.06 sec.
118800 frames of binary, time 811.21 sec.
122400 frames of binary, time 827.99 sec.
126000 frames of binary, time 844.62 sec.
129600 frames of binary, time 861.72 sec.
133200 frames of binary, time 878.14 sec.
136800 frames of binary, time 895.02 sec.
140400 frames of binary, time 912.36 sec.
time 912.81 sec. Wrote 46800 frames per binary for 3 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not running registration, ops['do_registration']=0
binary path: 01_data/02_preprocessed_data/02_Psychedelics_L5b_suite2p/231113D_Sim-Cre/Saline_LSD/suite2p/plane0/data.bin
NOTE: applying default /home/meng/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 12
Binned movie of size [3900,512,512] created in 165.85 sec.
NOTE: FORCED spatial scale ~12 pixels, time epochs 3.25, threshold 48.75 
0 ROIs, score=520.15
Detected 483 ROIs, 74.89 sec
After removing overlaps, 483 ROIs remain
----------- Total 241.48 sec.
----------- EXTRACTION
Masks created, 0.79 sec.
/home/meng/anaconda3/envs/2p/lib/python3.10/site-packages/suite2p/extraction/extract.py:125: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  Fi[n] = np.dot(data[:, cell_ipix[n]], cell_lam[n])
Extracted fluorescence from 483 ROIs in 46800 frames, 191.22 sec.
----------- Total 192.25 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- SPIKE DECONVOLUTION
----------- Total 0.84 sec.
Plane 0 processed in 434.92 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 1 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not running registration, ops['do_registration']=0
binary path: 01_data/02_preprocessed_data/02_Psychedelics_L5b_suite2p/231113D_Sim-Cre/Saline_LSD/suite2p/plane1/data.bin
NOTE: applying default /home/meng/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 12
Binned movie of size [3900,512,512] created in 171.09 sec.
NOTE: FORCED spatial scale ~12 pixels, time epochs 3.25, threshold 48.75 
0 ROIs, score=557.70
Detected 250 ROIs, 53.83 sec
After removing overlaps, 250 ROIs remain
----------- Total 225.38 sec.
----------- EXTRACTION
Masks created, 0.49 sec.
Extracted fluorescence from 250 ROIs in 46800 frames, 172.57 sec.
----------- Total 173.18 sec.
----------- CLASSIFICATION
['npix_norm', 'compact', 'skew']
----------- SPIKE DECONVOLUTION
----------- Total 0.42 sec.
Plane 1 processed in 399.10 sec (can open in GUI).
>>>> skipping flyback PLANE 2
total = 1747.42 sec.
Creating combined view
Traceback (most recent call last):
  File "/media/meng/Data/Meng_Psychedelics/02_code/02_prism_soma_dendrite/run_suite2p.py", line 116, in <module>
    output_ops = suite2p.run_s2p(ops=ops, db=db)
  File "/home/meng/anaconda3/envs/2p/lib/python3.10/site-packages/suite2p/run_s2p.py", line 556, in run_s2p
    io.combined(save_folder, save=True)
  File "/home/meng/anaconda3/envs/2p/lib/python3.10/site-packages/suite2p/io/save.py", line 131, in combined
    meanImgE[np.ix_(yrange, xrange)] = ops["meanImgE"]
KeyError: 'meanImgE'
```

### Version information:

suite2p v0.14.3

**Comment by carsen-stringer** [comment]
please try the latest suite2p version `pip install suite2p==0.99rc` and reopen the issue if the behavior is replicated in the new version
