### ISSUE TITLE
BUG: Error with registration/ROI extraction

### ISSUE THREAD

**Issue by kyesther00** [MouseLand/suite2p#1087]
### Describe the issue:

I've been using Suite2p fine for the past few weeks but today it gave me this error during registration for a recording I've previously processed without any issues and I'm not sure what the problem is.

### Reproduce the code example:

```python
n/a
```

### Error message:

```shell
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\runpy.py", line 197, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 84, in <module>
    main()
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 77, in main
    run_s2p(ops, db)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 547, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 342, in run_plane
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops,
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 114, in pipeline
    registration_outputs = registration.registration_wrapper(
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py", line 641, in registration_wrapper
    outputs = compute_reference_and_register_frames(f_align_in, f_align_out=f_align_out,
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py", line 464, in compute_reference_and_register_frames
    f_align_out[k:min(k + batch_size, n_frames)] = frames
  File "C:\Users\yk623\AppData\Local\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\binary.py", line 118, in __setitem__
    self.file[indices] = np.minimum(data, 2**15 - 2).astype("int16")
>>>ERROR<<<
ValueError: could not broadcast input array from shape (500,512,512) into shape (414,512,512)
Interrupted by error (not finished)
```

### Version information:

suite2p v0.14.3

**Comment by rbondare** [comment]
same error here
