### ISSUE TITLE
BUG: Value error after manual labelling extraction

### ISSUE THREAD

**Issue by Nique19351** [MouseLand/suite2p#1127]
### Describe the issue:

I recently began using suite2p to identify cells after 2 photon imaging. But, after manually labelling and trying to extract the ROIs, I receive an error message regarding the frames of the file. Is there anything I can do to move forward without erasing my progress?

### Reproduce the code example:

```python
I didn't write any code, only tried to extract ROIs after manually labelling.
```

### Error message:

```shell
Traceback (most recent call last):
  File "/opt/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/gui/drawroi.py", line 448, in proc_ROI
    F, Fneu, F_chan2, Fneu_chan2, spks, ops, stat = masks_and_traces(
  File "/opt/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/gui/drawroi.py", line 56, in masks_and_traces
    F, Fneu, F_chan2, Fneu_chan2 = extract_traces_from_masks(ops, manual_cell_masks,
  File "/opt/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/extraction/extract.py", line 145, in extract_traces_from_masks
    with BinaryFile(Ly=ops["Ly"], Lx=ops["Lx"], filename=ops["reg_file"]) as f:
  File "/opt/anaconda3/envs/suite2p/lib/python3.9/site-packages/suite2p/io/binary.py", line 36, in __init__
    raise ValueError(
ValueError: need to provide number of frames n_frames when writing file
```

### Version information:

Latest version

**Comment by simo-91** [comment]
Hi,
are you working on two different machines by any chance? I used to get that error when manually addind ROIs on my macOS after processing on Linux Mint.
