### ISSUE TITLE
Errors when trying to launch the program

### ISSUE THREAD

**Issue by MrCapsaicin** [MouseLand/suite2p#114]
Hello!

I have just installed the program, following the steps from the README, I used the Anaconda prompt to move the suite2p into a clean environment, I also un/reinstalled the module named PyQt5.sip

When I try to run the GUI:

**(suite2p) C:\Users\crash>python -m suite2p**

I get this errors:

**Traceback (most recent call last):
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\__init__.py", line 1, in <module>
    import suite2p.register
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\register.py", line 9, in <module>
    from suite2p import nonrigid, utils
  File "C:\Users\crash\AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\utils.py", line 2, in <module>
    from natsort import natsorted
ModuleNotFoundError: No module named 'natsort'****

What can I do to fix it?

Thank you very much!

**Comment by MrCapsaicin** [comment]
Thanks for the superfast response, I'm pretty naive in computer programming, and i couldn't figure it out by myself.

David

**Comment by marius10p** [comment]
No worries, let us know if you need any more help.
