### ISSUE TITLE
Recurring classifier error - IndexError: index 99 is out of bounds for axis 0 with size 99

### ISSUE THREAD

**Issue by dmnburrows** [MouseLand/suite2p#123]
I am loading in a tiff with 5 planes (18,000 frames per plane) - for some planes the registration/segmentation and extractions steps work fine, but then for others I get the following error:

/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/classifiers/classifier_user.npy
===== 2018.11.22 16:11:27 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "/Users/dominicburrows/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/__main__.py", line 32, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/run_s2p.py", line 190, in run_s2p
>>>ERROR<<<
    iscell = classifier.run(classfile, stat)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/classifier.py", line 77, in run
    probcell = model.apply(stat)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/classifier.py", line 31, in apply
    y_pred     = probability(stat,self.stats,self.iscell,self.keys)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/classifier.py", line 62, in probability
    logp = get_logp(test_stats, grid, p)
  File "/Users/dominicburrows/anaconda3/lib/python3.6/site-packages/suite2p/classifier.py", line 42, in get_logp
    logp[:,n] = np.log(p[ibin,n] + 1e-6) - np.log(1-p[ibin,n] + 1e-6)
IndexError: index 99 is out of bounds for axis 0 with size 99
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
I think this has been resolved offline, although not totally sure why (potentially a data type error), please reopen this if the error occurs again

**Comment by carsen-stringer** [comment]
Sometimes small cells (single pixel cells) will have a NaN assigned as their footprint, the latest version should fix this problem

**Comment by carsen-stringer** [comment]
Has this been resolved? Please close the issue if this error is no longer happening, thanks

**Comment by carsen-stringer** [comment]
I'm going to close this because I think we figured it out :)

**Comment by Cumol** [comment]
I am getting this error with some of my tif files (2 out of 8 tif files from the same experiment).

I am on the 0.4.5 version right now because of the tif issue. So if this is already resolved in later updates. I am sorry for bringing it up.

I was just puzzled that it only shows up in some tif files but not others.
