### ISSUE TITLE
Error with celldetect2.py

### ISSUE THREAD

**Issue by ivapl** [MouseLand/suite2p#124]
Hi, I'm using the python version and I'm having an error shown below. Would you be so kind to give me some suggestions where could be the source of it? Thanks in advance!

_foundpre-registered binaries
skipping registration...
[12 12]
nt0=10
(15, 512, 512)
6.0
here
ROIs: 200, cost: 0.5412, time: 60.9363
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/suite2p/test1.py", line 69, in <module>
    opsEnd=run_s2p(ops=ops,db=db)
  File "C:\Users\venv\suite2p\lib\site-packages\suite2p\run_s2p.py", line 176, in run_s2p
    ops1[ipl[0]] = utils.get_cells(ops1[ipl[0]])
  File "C:\Users\venv\suite2p\lib\site-packages\suite2p\utils.py", line 431, in get_cells
    ops, stat = celldetect2.sourcery(ops)
  File "C:\Users\venv\suite2p\lib\site-packages\suite2p\celldetect2.py", line 620, in sourcery
    L   = np.append(L, np.zeros((Lyc, Lxc, newcells), 'float32'), axis =-1)
  File "C:\Users\venv\suite2p\lib\site-packages\numpy\lib\function_base.py", line 4528, in append
    return con_

**Comment by ivapl** [comment]
It's now woking. I  just uninstalled suite2p then reinstall it through Anaconda. I previously install it through PyCharm.
