### ISSUE TITLE
cannot run "python -m suite2p" on Windows10

### ISSUE THREAD

**Issue by vickerse1** [MouseLand/suite2p#174]
I followed all instructions literally, including all upgrades, on Windows 10, and received the following error:

---------------------------------
(suite2p) C:\Users\McCormick Lab\Documents\Python\suite2p>python -m suite2p
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\McCormick Lab\Documents\Python\suite2p\suite2p\__init__.py", line 1, in <module>
    import suite2p.register
  File "C:\Users\McCormick Lab\Documents\Python\suite2p\suite2p\register.py", line 9, in <module>
    from suite2p import nonrigid, utils
  File "C:\Users\McCormick Lab\Documents\Python\suite2p\suite2p\utils.py", line 12, in <module>
    from ScanImageTiffReader import ScanImageTiffReader
ModuleNotFoundError: No module named 'ScanImageTiffReader'
-----------------------------------------------------------------

I'm running python 3.7.1.

Could you please tell me exactly what I need to do to get it to run?

Thanks,

Evan

**Comment by carsen-stringer** [comment]
Sorry this hasn't been added to the setup.py to auto install, the package is scanimage-tiff-reader:
```
pip install scanimage-tiff-reader
```

**Comment by vickerse1** [comment]
thanks now runs great.
