### ISSUE TITLE
ValueError: could not broadcast input array from shape (118,117) into shape (120,120), when loading any .tif file

### ISSUE THREAD

**Issue by Tono2P** [MouseLand/suite2p#178]
I'm transitioning from CaImAn to sweet2p. I managed to solve my first issue on my own ('total number of frames should be at least 50' for .tif files with 1000 frames) by switching form the pip installed version of the code to the github version and checking out to the sparse_mode branch. However now I get the following error when running it with any .tif file I have (less than 1GB files, FIJI generated ones saved as OME tiffs):

Found 1 tifs
1000
time 0.7949. Wrote tifs to binaries for 1 planes
computed reference frame for registration in time 16.40
registered 1000/1000 frames in time 10.88
registered 1000/1000 frames in time 10.88
===== 2019.05.16 15:05:56 =====
>>>ERROR<<<
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\suite2p\suite2p\regmetrics.py", line 113, in pc_register_worker
    maskMulNR, maskOffsetNR, cfRefImgNR = nonrigid.prepare_masks(refImg, ops)
  File "C:\Users\suite2p\suite2p\nonrigid.py", line 93, in prepare_masks
    cfRefImg1[n,0,:,:] = (cfRefImg.astype('complex64'))
ValueError: could not broadcast input array from shape (118,117) into shape (120,120)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\suite2p\suite2p\__main__.py", line 32, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\suite2p\suite2p\run_s2p.py", line 199, in run_s2p
>>>ERROR<<<
    ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
>>>ERROR<<<
  File "C:\Users\suite2p\suite2p\register.py", line 854, in register_binary
>>>ERROR<<<
    ops = regmetrics.get_pc_metrics(ops)
  File "C:\Users\suite2p\suite2p\regmetrics.py", line 151, in get_pc_metrics
>>>ERROR<<<
    ops['smooth_sigma'], ops['block_size'], ops['maxregshift'], ops['maxregshiftNR'], ops['1Preg'])
  File "C:\Users\suite2p\suite2p\regmetrics.py", line 98, in pc_register
    results = p.map(pc_register_worker, dsplit[ix:ix+nc])
  File "C:\Users\Anaconda3\lib\multiprocessing\pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Anaconda3\lib\multiprocessing\pool.py", line 644, in get
>>>ERROR<<<
    raise self._value
ValueError: could not broadcast input array from shape (118,117) into shape (120,120)
Interrupted by error (not finished)

Thank you so much for your time.

**Comment by carsen-stringer** [comment]
hey sorry about this - there is a bug in regmetrics if you don't have >1500 frames. It will no longer compute regmetrics if you have less than 2000 frames, please pull the latest version

**Comment by Tono2P** [comment]
Thanks a lot for the quick response and a great pipeline.
