### ISSUE TITLE
ERROR MOTION CORRECTION

### ISSUE THREAD

**Issue by Mocambo90** [MouseLand/suite2p#185]
https://github.com/MouseLand/suite2p/issues
Hi, first congrats for your pipeline.
I want to ask you a question: I have times series (306x120, block size: 306,120, max reg: 3.06) and when I tried to perform the motion correction I got the following error.
Am I using in an incorrect way the parameters? 

>>>ERROR<<<
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\admin\Anaconda3\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 192, in phasecorr_worker
    ymax, xmax, cmax,snr = getXYup(cc, (lcorr,lpad, Lyhalf, Lxhalf), ops)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 126, in getXYup
    ccmat[j,:,:] = cc[j, (mxpt[0][j] -lpad):(mxpt[0][j] +lpad+1), (mxpt[1][j] -lpad):(mxpt[1][j] +lpad+1)]
ValueError: could not broadcast input array from shape (6,7) into shape (7,7)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\admin\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\admin\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\__main__.py", line 32, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\run_s2p.py", line 171, in run_s2p
    ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 363, in register_binary
    op = register_binary(op)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 388, in register_binary
    refImg = pick_init(ops)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 338, in pick_init
    refImg = refine_init_init(ops, frames, refImg)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 321, in refine_init_init
    freg, ymax, xmax, cmax, yxnr = phasecorr(frames, [maskMul, maskOffset, cfRefImg], ops)
  File "C:\Users\admin\Anaconda3\lib\site-packages\suite2p\register.py", line 224, in phasecorr
    results = p.map(phasecorr_worker, dsplit)
  File "C:\Users\admin\Anaconda3\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\admin\Anaconda3\lib\multiprocessing\pool.py", line 657, in get
>>>ERROR<<<
    raise self._value
ValueError: could not broadcast input array from shape (6,7) into shape (7,7)
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
We've recently updated the pipeline, please see the new installation details on the wiki. Can you please update to the latest version and see if you're still getting this error?

**Comment by carsen-stringer** [comment]
I just noticed that you made your block size the same size as your images. you should keep that smaller - it is the size of the tiles for non-rigid registration. Maybe 64,64 is good in this case. You can also turn off non-rigid for these small frames with ops['nonrigid'].

**Comment by Mocambo90** [comment]
Hi, thanks for your reply! I tried what you suggested but I get always the
same error message, after the registration

Il giorno ven 30 ago 2019 alle ore 18:28 carsen-stringer <
notifications@github.com> ha scritto:

**Comment by carsen-stringer** [comment]
I think the issue here (if it's not the nonrigid) could be your setting of maxregshift? That should be a number between 0 and 1 (it's a percentage of the frame size)

**Comment by Mocambo90** [comment]
Hi, thank you very much for you response and sorry for my late reply. I
updated the version of suite2p and I solved the problem.
Thanks again!

Il giorno ven 29 nov 2019 alle ore 15:29 carsen-stringer <
notifications@github.com> ha scritto:
