### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by leedoyun** [MouseLand/suite2p#189]
After the update on Jun 11 a syntax error occurs at line 164 of Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui.py

**Comment by carsen-stringer** [comment]
sorry about that I think I fixed it, try
~~~
pip install suite2p==1.0.5
~~~

**Comment by leedoyun** [comment]
It is working but there are another errors.
I doesn't save results to matlab file.

>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\leed\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\leed\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\leed\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 28, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\leed\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 219, in run_s2p
    io.savemat(matpath, {'stat': stat,
NameError: name 'stat' is not defined
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
ah sorry I should have tested that, try now. FYI you can also save to *.mat now from the GUI. it's in 0.6.2 (or run `pip install suite2p --upgrade`)
