### ISSUE TITLE
Errors message after ROI detection Interrupted by error (not finished)

### ISSUE THREAD

**Issue by LaureKCL** [MouseLand/suite2p#208]
After few error messages I uninstalled Anaconda. Now I have the latest version of Anaconda 3.7 and suite2p 0.6.8  but I got the same error messages. Computer on Windows 10 Enterprise.
Couldn't find any answer on internet.

Thanks for your help.
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\k1517871\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\k1517871\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\__main__.py", line 28, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\run_s2p.py", line 203, in run_s2p
>>>ERROR<<<
    ops1[ipl] = roiextract.roi_detect_and_extract(ops1[ipl])
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\roiextract.py", line 219, in roi_detect_and_extract
>>>ERROR<<<
    ops, stat = sourcery.sourcery(ops)
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\sourcery.py", line 516, in sourcery
>>>ERROR<<<
    stat = postprocess(ops, stat, Ucell, codes)
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\sourcery.py", line 523, in postprocess
>>>ERROR<<<
    stat = get_stat(ops, stat, Ucell, codes)
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\sourcery.py", line 253, in get_stat
>>>ERROR<<<
    yp, xp = extendROI(ypix,xpix,Ly,Lx, int(np.mean(d0)))
  File "C:\Users\k1517871\AppData\Roaming\Python\Python37\site-packages\suite2p\sourcery.py", line 333, in extendROI
>>>ERROR<<<
    yu = np.unique(yx, axis=1)
  File "C:\Users\k1517871\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\arraysetops.py", line 276, in unique
>>>ERROR<<<
    ar = ar.reshape(orig_shape[0], -1)
ValueError: cannot reshape array of size 0 into shape (0,newaxis)
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
it seems like it's not finding any cells. what is the `ops['diameter']` you are setting? The units for this is pixels - It might be too large?

**Comment by craddr** [comment]
update all packages in suite2p environment

ie 

cd [user\Anaconda3\envs]
conda activate suite2p
conda update --all


^^ that's what fixed the error for me
if this doesn't help, might also be worth updating python & packages on which s2p is dependent??

**Comment by chrytsi** [comment]
Hi,

First of all, thank you for your great work!
After upgrading suite2p I am now also getting an error (during spike deconvolution) prior and after updating all packages.

`----------- SPIKE DECONVOLUTION
Total 25.61 sec.
===== 2019.08.21 17:08:38 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda2\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\Admin\Anaconda2\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Admin\Anaconda2\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 28, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\Admin\Anaconda2\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 219, in run_s2p
    io.savemat(matpath, {'stat': stat,
NameError: name 'stat' is not defined
`
Do you have any suggestions?

**Comment by carsen-stringer** [comment]
hmm maybe try deleting the previously run files and try running again? if stat doesn't exist maybe it didn't find cells still

**Comment by chrytsi** [comment]
Thanks for getting back to me.
stat was actually not defined in run_s2p.py when I upgraded using pip, whereas it is defined in the code on github's master branch.
Has anyone else had problems with the pip version?

**Comment by chrytsi** [comment]
Hi,
thanks for getting back to me. 
stat was actually not defined in run_s2p.py after I had upgraded with pip. It was defined, however on github's master branch. After upgrading again it worked fine...
