### ISSUE TITLE
drawroi missing?

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#218]
After installing the latest version, the GUI won't open because `drawroi` is missing. 

```
Traceback (most recent call last):
  File "/Users/hotte/miniconda3/envs/analysis2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "miniconda3/envs/analysis2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "suite2p-python/suite2p/__main__.py", line 4, in <module>
    from suite2p import run_s2p, gui2p
  File "suite2p-python/suite2p/gui2p.py", line 9, in <module>
    from suite2p import fig, gui, classifier, visualize, reggui, classgui, merge, drawroi
```

https://github.com/MouseLand/suite2p/blob/0ec481eed53c19732927f94b0b907e4480088c75/suite2p/gui2p.py#L9

**Comment by carsen-stringer** [comment]
oops I added this file
