### ISSUE TITLE
add cell chosen statistics

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#23]

**Comment by marius10p** [comment]
===== 2018.08.04 20:08:27 =====
Traceback (most recent call last):
  File "D:\Github\suite2p\suite2p\gui2p.py", line 378, in plot_clicked
    self.ichosen_stats()
  File "D:\Github\suite2p\suite2p\gui2p.py", line 393, in ichosen_stats
    self.ROIstats[k].setText(key+str(ival))
IndexError: list index out of range
