### ISSUE TITLE
Most recent Github version does not load classifiers or add current data to clasifier

### ISSUE THREAD

**Issue by mkm4884** [MouseLand/suite2p#251]
Hello, 

When trying to add current data to a classifier, I receive the following error:

```
Adding current dataset to classifier  
===== 2019.10.25 15:10:23 =====  
Traceback (most recent call last):
  File "C:\Users\user\repos\suite2p\suite2p\gui\classgui.py", line 24, in <lambda>
    parent.addtoclass.clicked.connect(lambda: add_to(parent))
  File "C:\Users\user\repos\suite2p\suite2p\gui\classgui.py", line 183, in add_to
    stats = classifier.get_stat_keys(parent.stat, parent.model.keys)
AttributeError: 'MainWindow' object has no attribute 'model'
```

When loading classifiers, the following errors displayed:

```
loading classifier  C:/Users/user/Documents/test_classifier.npy
===== 2019.10.25 14:10:59 =====
Traceback (most recent call last):
  File "C:\Users\user\repos\suite2p\suite2p\gui\menus.py", line 65, in <lambda>
    parent.loadClass.triggered.connect(lambda: classgui.load_classifier(parent))
  File "C:\Users\user\repos\suite2p\suite2p\gui\classgui.py", line 34, in load_classifier
    parent.class_activated()
AttributeError: 'MainWindow' object has no attribute 'class_activated'
```
```
loading classifier  C:\Users\user\repos\suite2p\suite2p\classifiers/classifier_user.npy
===== 2019.10.25 14:10:53 =====
Traceback (most recent call last):
  File "C:\Users\user\repos\suite2p\suite2p\gui\menus.py", line 69, in <lambda>
    parent.loadUClass.triggered.connect(lambda: classgui.load_default_classifier(parent))
  File "C:\Users\user\repos\suite2p\suite2p\gui\classgui.py", line 51, in load_default_classifier
    parent.class_activated()
AttributeError: 'MainWindow' object has no attribute 'class_activated'
```

**Comment by carsen-stringer** [comment]
sorry about that, I think I've found all the bugs, please clone the latest version and comment if you still have issues

**Comment by sblumenstock** [comment]
Hi Carsen,

I have a related issue with building and loading custom classifiers. Building a classifier works fine, loading it right after building, also. However, when I close and reopen suite2p and want to load my classifier and save new data to it, suite2p saves to classifier_user instead of my custom-built classifier.

In the terminal, it looks like this:
``` 
loading classifier  C:/Users/myname/Downloads/suite2p_repo/suite2p/suite2p/classifiers/my_classifier.npy
Adding current dataset to classifier
saving classifier in C:\Users\myname\Downloads\suite2p_repo\suite2p\suite2p\classifiers/classifier_user.npy
```

I will need at least two custom-built classifiers for my analysis, so I would greatly appreciate your advice on how to solve this.

**Comment by carsen-stringer** [comment]
thanks for catching this bug, it should be working now in the latest github, please clone the repository and comment if you still have issues
