### ISSUE TITLE
New to Anaconda, cannot instal suite2p

### ISSUE THREAD

**Issue by ondra6** [MouseLand/suite2p#256]
Dear colleagues,
I would like to start working with suit2p, so I installed the available version of Anaconda (3.8 64bit for Win10). When I follow the instructions I am getting this error (the report is bellow). I tried to go through the mentioned files, or google the indicated strings, but I was not successful.

May be it is a simple isssue, but I cannot see it. Could you please help me with this?
I doublechecked that I am in the folder to which I copy the environment.yml file.

Thank you.
Ondrej

(base) C:\functions>conda env create -f environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
        directory=os.getcwd())
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
        if spec.can_handle():
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 136, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 99, in compose_document
        self.parser.get_event()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 166, in get_event
        self.current_event = self.state()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 244, in parse_document_end
        token = self.scanner.peek_token()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 173, in peek_token
        self.fetch_more_tokens()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 273, in fetch_more_tokens
        return self.fetch_value()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 626, in fetch_value
        self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
      in "<unicode string>", line 114, column 71:
         ... r-bar top-0 left-0" style="width: 0%;"></span>
                                             ^ (line: 114)

`$ C:\ProgramData\Anaconda3\Scripts\conda-env-script.py create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Ondrej Novak
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\
                          Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\
                          bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\
                          system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windo
                          wsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\MATLAB\R2018a\bin;C:
                          \WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syste
                          m32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\Ondrej
                          Novak\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Ondrej Novak\.condarc
 populated config files : C:\Users\Ondrej Novak\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.1
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Ondrej Novak\.conda\pkgs
                          C:\Users\Ondrej Novak\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Ondrej Novak\.conda\envs
                          C:\Users\Ondrej Novak\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

**Comment by ondra6** [comment]
Ok, I deleted all spaces in environment.zml and the error is gone. However, there is a new one>
AttributeError("'str' object has no attribute 'copy'")

**Comment by ondra6** [comment]
(base) D:\>conda env create -f environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
        directory=os.getcwd())
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
        if spec.can_handle():
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 151, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 137, in from_yaml
        data = validate_keys(data, kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 35, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'

`$ C:\ProgramData\Anaconda3\Scripts\conda-env-script.py create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\Ondrej Novak
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\
                          Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\
                          bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\Windows\
                          system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Windo
                          wsPowerShell\v1.0;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\Intel\Intel(R)
                          Management Engine Components\IPT;C:\Program Files\MATLAB\R2018a\bin;C:
                          \WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syste
                          m32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\Ondrej
                          Novak\AppData\Local\Microsoft\WindowsApps
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Ondrej Novak\.condarc
 populated config files : C:\Users\Ondrej Novak\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       virtual packages : __cuda=9.1
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Ondrej Novak\.conda\pkgs
                          C:\Users\Ondrej Novak\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Ondrej Novak\.conda\envs
                          C:\Users\Ondrej Novak\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

**Comment by ondra6** [comment]
Dear colleagues. Mea culpa. It was my fault. I downloaded environment.yml using mouse right button click and not opening the file that is downloaded within the archive file. Now everything works perfectly.
Thanks. Ondrej
