### ISSUE TITLE
Some help with running Suite2P (python)

### ISSUE THREAD

**Issue by BScThomas** [MouseLand/suite2p#261]
Hello there,

I'm a bachelor biologist currently doing my bachelor internship and am trying to run suite2p.
I however get these errors thrown at me, and I have no idea what they all mean.
Might there be someone who can help me?

Note that this is done on a simple PC with an HDD. last name hidden with -.

>

{'data_path': ['C:/Users/-/Documents/Sequence_001'], 'subfolders': [], 'save_path0': 'C:/Users/-/Documents/Results', 'fast_disk': 'C:/Users/-/Documents/Results'}
** Found 10705 tifs - converting to binary **
NOTE: ScanImageTiffReader not working for this tiff type, using scikit-image
2000 frames of binary, time 108.59 sec.
4000 frames of binary, time 218.99 sec.
6000 frames of binary, time 328.95 sec.
8000 frames of binary, time 437.08 sec.
10000 frames of binary, time 546.63 sec.
time 584.85 sec. Wrote tifs to binaries for 1 planes
 PLANE 0 
----------- REGISTRATION
registering 10705 frames
===== 2019.11.20 11:11:17 =====
ERROR
Traceback (most recent call last):
  File "C:\Users\-\Documents\Anaconda\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
ERROR
    "____main____", mod_spec)
  File "C:\Users\-\Documents\Anaconda\envs\suite2p\lib\runpy.py", line 85, in _run_code
ERROR
    exec(code, run_globals)
  File "C:\Users\-\Documents\suite2p-master\suite2p\__main__.py", line 24, in <module>
ERROR
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\-\Documents\suite2p-master\suite2p\run_s2p.py", line 225, in run_s2p
ERROR
    ops1[ipl] = register.register_binary(ops1[ipl]) # register binary
  File "C:\Users\-\Documents\suite2p-master\suite2p\registration\register.py", line 356, in register_binary
ERROR
    refImg, bidi = reference.compute_reference_image(ops)
  File "C:\Users\-\Documents\suite2p-master\suite2p\registration\reference.py", line 108, in compute_reference_image
ERROR
    bidi = bidiphase.compute(frames)
  File "C:\Users\-\Documents\suite2p-master\suite2p\registration\bidiphase.py", line 42, in compute
ERROR
    ix = np.argmax(cc[(np.arange(-10,11,1) + np.floor(Lx/2)).astype(int)])
IndexError: index -9 is out of bounds for axis 0 with size 3
Interrupted by error (not finished)<

**Comment by carsen-stringer** [comment]
It looks like you're running the github version but it's somehow also calling the pip version. I'm not sure what's in "suite2p_main.py" but the paths are confused in there somehow. I recommend running the pipeline using the GUI. Please follow the install options on the main readme

**Comment by carsen-stringer** [comment]
I'm going to close this due to inactivity (and because suite2p_main.py isn't our function). please comment if you have more questions.
