### ISSUE TITLE
Troubles running suite2p on windows

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#297]
I installed suite2p as suggested, the GUI works as intended with the still lasting problem that it does not detect TIFF files that do not have the .tif ending (see error output at the end) which is why I have been using a modified version of [this](https://github.com/MouseLand/suite2p/blob/master/jupyter/run_pipeline_tiffs_or_batch.ipynb) jupyter notebook to run the pipeline on ubuntu. And that works fine.

When I run `jupyter notebook` in the suite2p conda environment and then run the following:

```
import numpy as np
import os.path
import sys

import suite2p
from suite2p import run_s2p
```
I get the following error:

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-7b21ea8f19fb> in <module>
----> 1 import suite2p
      2 from suite2p import run_s2p

ModuleNotFoundError: No module named 'suite2p'

```
So I figured I should check if suite2p is in the path and ran `sys.path`

```
['C:\\Users\\Dr. Siemens\\Desktop',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\python37.zip',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\DLLs',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib',
 'C:\\Users\\Dr. Siemens\\Anaconda3',
 '',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages\\acq4-0.9.3_develop_7cf4a7498e-py3.7.egg',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\Dr. Siemens\\Anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\Dr. Siemens\\.ipython']
```
For some reason, it does not contain the path to the suite2p environment so I tried some options for sys.path

`sys.path.insert(0,'C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\')`

got me to:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-7b21ea8f19fb> in <module>
      1 import suite2p
----> 2 from suite2p import run_s2p

ImportError: cannot import name 'run_s2p' from 'suite2p' (unknown location)

```

then I restarted the kernel and did `sys.path.insert(0,'C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\suite2p')` instead

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-7b21ea8f19fb> in <module>
----> 1 import suite2p
      2 from suite2p import run_s2p

ModuleNotFoundError: No module named 'suite2p'
```
I also tried pointing to the packages directly with `sys.path.insert(0,'C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\Lib\\site-packages')` with the same output.

When I change sys.path to the github foder `sys.path.insert(0,'C:\\Users\\Dr. Siemens\\suite2p')` I get the following output:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-7b21ea8f19fb> in <module>
----> 1 import suite2p
      2 from suite2p import run_s2p

~\suite2p\suite2p\__init__.py in <module>
----> 1 import suite2p.run_s2p
      2 
      3 name = "suite2p"

~\suite2p\suite2p\run_s2p.py in <module>
      3 import time, os, shutil
      4 from scipy.io import savemat
----> 5 from .io import tiff, h5, save
      6 from .registration import register, metrics, reference
      7 from .extraction import extract, dcnv

~\suite2p\suite2p\io\__init__.py in <module>
----> 1 from . import utils, h5, save, tiff

~\suite2p\suite2p\io\utils.py in <module>
      1 import numpy as np
      2 import os
----> 3 from natsort import natsorted
      4 import glob
      5 

ModuleNotFoundError: No module named 'natsort'
```
The only thing that ended up working is doing this:

```
sys.path.insert(0,'C:\\Users\\Dr. Siemens\\suite2p')
sys.path.insert(0,"C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\suite2p")
sys.path.insert(0,"C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\suite2p\\DLLs")
sys.path.insert(0,"C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\suite2p\\lib")
sys.path.insert(0,"C:\\Users\\Dr. Siemens\\Anaconda3\\envs\\suite2p\\lib\\site-packages")

```

Which is probably not the intended way.

+not finding files as tiffs+
Could not find any tiffs
>>>ERROR<<<
```
Traceback (most recent call last):
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 62, in <module>
    parse_arguments()
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 55, in parse_arguments
    run_s2p.run_s2p(ops, db)
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 221, in run_s2p
    ops1 = tiff.tiff_to_binary(ops)
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 136, in tiff_to_binary
>>>ERROR<<<
    ops1, fs, reg_file, reg_file_chan2 = utils.find_files_open_binaries(ops1, False)
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\utils.py", line 216, in find_files_open_binaries
>>>ERROR<<<
    fs, ops2 = get_tif_list(ops1[0])
  File "C:\Users\Dr. Siemens\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\utils.py", line 153, in get_tif_list
    raise Exception('no tiffs')
Exception: no tiffs
Interrupted by error (not finished)
```

**Comment by carsen-stringer** [comment]
This is the correct way to do things:
`sys.path.insert(0,'C:/Users/Dr. Siemens/suite2p')`
you may just need to `pip install natsort`. 

Are you using the `tiff_list` option? You have to use that option for it to work. If you are then I can test and see if it's broken in the new version.

**Comment by Cumol** [comment]
Installing natsort did not solve the issue. It have me the same errors. It only worked for me when I pointed sys.path to all the subdirectories.

**Comment by Cumol** [comment]
I use the tiff_list option in the ops when using the jupyter notebook. There is no tiff_list option in the GUI

**Comment by Cumol** [comment]
By the way, this was solved by updating ipython and jupyter in the suite2p environment
