### ISSUE TITLE
Dependency conflict with pandas

### ISSUE THREAD

**Issue by simon-ball** [MouseLand/suite2p#298]
Once Suite2p is installed, I am unable to import `pandas`, due to some kind of conflict within `numpy`. As far as I can tell, the issue appears to centre around the use of `mkl_fft` and `intel-numpy`, resulting in an inconsistent Numpy installation. I am not entirely sure why `pandas` is the only package that seems to have problems with this.

How much performance is gained by using the Intel-compiled `numpy` and `mkl_fft` libraries versus using the default `numpy` and FFT-libraries?

Two approaches to reproduce:
### Installing latest version of Suite2p from Git:
```
conda create --name s2p1 python=3.6
conda activate s2p1
pip install git+git://github.com/MouseLand/suite2p
pip install pandas
python -c "import pandas"

>> Traceback (most recent call last):
>> File "<string>", line 1, in <module>
>> File "C:\Users\simoba\AppData\Local\Continuum\anaconda3\envs\s2p1\lib\site-packages\pandas\__init__.py", line 31, in <module>
    from pandas._libs import hashtable as _hashtable, lib as _lib, tslib as _tslib
>>File "C:\Users\simoba\AppData\Local\Continuum\anaconda3\envs\s2p1\lib\site-packages\pandas\_libs\__init__.py", line 3, in <module>
    from .tslibs import (
>>File "C:\Users\simoba\AppData\Local\Continuum\anaconda3\envs\s2p1\lib\site-packages\pandas\_libs\tslibs\__init__.py", line 3, in <module>
    from .conversion import localize_pydatetime, normalize_date
>>File "__init__.pxd", line 918, in init pandas._libs.tslibs.conversion
>>ValueError: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216 from C header, got 192 from PyObject
```

### Installing Suite2p from pip
```
conda create --name s2p2 python=3.6
conda activate s2p2
pip install pandas suite2p
python -c "import pandas"

>>Traceback (most recent call last):
>>File "<string>", line 1, in <module>
>>File "C:\Users\simoba\AppData\Local\Continuum\anaconda3\envs\s2p2\lib\site-packages\pandas\__init__.py", line 17, in <module>
    "Unable to import required dependencies:\n" + "\n".join(missing_dependencies)
ImportError: Unable to import required dependencies:
numpy: Something is wrong with the numpy installation. While importing we detected an older
version of numpy in ['C:\\Users\\simoba\\AppData\\Local\\Continuum\\anaconda3\\envs\\s2p2
\\lib\\site-packages\\numpy']. One method of fixing this is to repeatedly uninstall numpy until none
is found, then reinstall this version.
```
The total list of packages installed at the point at which this error arises is given below (courtesy of `pip list`:

In both cases, the list of installed packages at the time of the error on importing pandas is as follows (from `pip list`)
```
Package               Version            
--------------------- -------------------
certifi               2019.11.28         
cycler                0.10.0             
decorator             4.4.2              
h5py                  2.10.0             
icc-rt                2019.0             
imageio               2.8.0              
intel-numpy           1.15.1             
intel-openmp          2019.0             
joblib                0.14.1             
kiwisolver            1.1.0              
llvmlite              0.31.0             
matplotlib            3.1.3              
mkl                   2019.0             
mkl-fft               1.0.6              
mkl-random            1.0.1.1            
natsort               7.0.1              
networkx              2.4                
numba                 0.48.0             
numpy                 1.18.0             
pandas                1.0.1              
Pillow                7.0.0              
pip                   20.0.2             
pyparsing             2.4.6              
pyqtgraph             0.10.0             
python-dateutil       2.8.1              
pytz                  2019.3             
PyWavelets            1.1.1              
scanimage-tiff-reader 1.4.1              
scikit-image          0.16.2             
scikit-learn          0.22.2.post1       
scipy                 1.4.1              
setuptools            45.2.0.post20200209
six                   1.14.0             
suite2p               0.7.1              
tbb                   2019.0             
tbb4py                2019.0             
wheel                 0.34.2             
wincertstore          0.2 
```

In both cases, the error can be removed by removing `numpy` twice, and then reinstalling it:
```pip uninstall numpy
>> uninstalling numpy-1.18.1
pip uninstall numpy
>>uninstalling numpy-1.15.1
pip install numpy
>> Successfully installed numpy-1.18.1
python -c "import pandas"
```
After this process, the list of installed packages is as follows:
```
Package               Version            
--------------------- -------------------
certifi               2019.11.28         
cycler                0.10.0             
decorator             4.4.2              
h5py                  2.10.0             
icc-rt                2019.0             
imageio               2.8.0              
intel-openmp          2019.0             
joblib                0.14.1             
kiwisolver            1.1.0              
llvmlite              0.31.0             
matplotlib            3.1.3              
mkl                   2019.0             
mkl-fft               1.0.6              
mkl-random            1.0.1.1            
natsort               7.0.1              
networkx              2.4                
numba                 0.48.0             
numpy                 1.18.1             
pandas                1.0.1              
Pillow                7.0.0              
pip                   20.0.2             
pyparsing             2.4.6              
pyqtgraph             0.10.0             
python-dateutil       2.8.1              
pytz                  2019.3             
PyWavelets            1.1.1              
scanimage-tiff-reader 1.4.1              
scikit-image          0.16.2             
scikit-learn          0.22.2.post1       
scipy                 1.4.1              
setuptools            45.2.0.post20200209
six                   1.14.0             
suite2p               0.7.1              
tbb                   2019.0             
tbb4py                2019.0             
wheel                 0.34.2             
wincertstore          0.2  
```
The only change from the previous list of installed packages is that `intel-numpy  1.15.1` is no longer present

**Comment by carsen-stringer** [comment]
Why are you not using the `environment.yml` file to create your environment? That is strongly recommended to make sure that the mkl works correctly with mkl-fft and is fast. Your mkl-fft version is 1.0.6 not 1.0.10, which is the version installed with the environment file. Please try that and see if this error still occurs.

Note the mkl-fft package was recently updated, I will check that the latest version works as fast as the original, and the newest may not have this issue (even if 1.0.10 does). This package is VERY important to have fast registration.

**Comment by simon-ball** [comment]
I've been using `pip` for two reasons:
1) `ansible` does not have a reliable way to manipulate `conda` (that I know of), only `pip`
2) Other elements in the processing pipeline I am trying to deploy either exist only in `pip`, or exist only on github (from which I deploy using `pip`). 

I thoroughly agree with you that using `conda` is preferred as far as possible, but in my specific use-case, its limitations are, well, limiting. 

I will look into both ansible-conda integration, and whether pinning specific `mkl*` versions in `requirements.txt` have any effect.
