### ISSUE TITLE
gui2p.py points to incorrect location for default_ops

### ISSUE THREAD

**Issue by bf777** [MouseLand/suite2p#326]
Hi,

When we install suite2p and run `python -m suite2p`, we get the following error (for reference, we are using the conda environment setup of suite2p using Python 3.7.7 on Windows 10):

```
C:\Users\user\Miniconda3\envs\suite2p\lib\site-packages\numba\np\ufunc\parallel.py:355: NumbaWarning: The TBB threading layer requires TBB version 2019.5 or later i.e., TBB_INTERFACE_VERSION >= 11005. Found TBB_INTERFACE_VERSION = 11000. The TBB threading layer is disabled.
  warnings.warn(problem)
===== 2020.05.17 21:05:28 =====
Traceback (most recent call last):
  File "C:\Users\user\Miniconda3\envs\suite2p\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\user\Miniconda3\envs\suite2p\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\user\Miniconda3\envs\suite2p\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\user\Desktop\suite2p\suite2p\__init__.py", line 1, in <module>
    import suite2p.gui.gui2p
  File "C:\Users\user\Desktop\suite2p\suite2p\gui\__init__.py", line 1, in <module>
    from . import (buttons, classgui, drawroi, graphics, io, masks, gui2p, menus,
  File "C:\Users\user\Desktop\suite2p\suite2p\gui\gui2p.py", line 10, in <module>
    from ..utils import default_ops
ImportError: cannot import name 'default_ops' from 'suite2p.utils' (C:\Users\user\Desktop\suite2p\suite2p\utils.py)
```
I followed this traceback through the git repo and noticed that even though the `default_ops` function has been moved to `run_s2p.py` (as per [c108a77](https://github.com/MouseLand/suite2p/commit/c108a77e7fe224654127510b2eb32795ba2aa1dc)), `gui2p.py` still tries to import `default_ops` from `utils.py`. Would you be able to look into this? Thank you!

**Comment by carsen-stringer** [comment]
oops sorry about that I've fixed this! can you please pull the latest github? I am going to make a new pip soon as well

**Comment by bf777** [comment]
@carsen-stringer Thanks for making the change and pushing it to pip! However, when I try to install the package from pip, I get the following:
```
Collecting suite2p
  Using cached suite2p-0.7.2-py3-none-any.whl (616 kB)
Requirement already satisfied, skipping upgrade: natsort in c:\users\user\miniconda3\envs\suite2p\lib\site-packages (from suite2p) (7.0.1)
Requirement already satisfied, skipping upgrade: scanimage-tiff-reader in c:\users\user\miniconda3\envs\suite2p\lib\site-packages (from suite2p) (1.4.1)
ERROR: Could not find a version that satisfies the requirement rastermap>0.10.0 (from suite2p) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.1.0, 0.1.1, 0.1.2, 0.1.3)
ERROR: No matching distribution found for rastermap>0.10.0 (from suite2p)
```
I noticed that the `rastermap` dependency in `setup.py` was recently changed to `rastermap>0.10.0` - considering that the latest version of rastermap is `0.1.3`, is this a typo? Thank you again for looking into this!

**Comment by carsen-stringer** [comment]
ahhh thanks for reporting this so quickly! fixed this
~~~
pip install suite2p==0.7.3
~~~
