### ISSUE TITLE
Error during SPIKE DECON after latest update to suite2p 0.7.3

### ISSUE THREAD

**Issue by samihassan84** [MouseLand/suite2p#329]
Hi Carsen,
after updating to suite2p 0.7.3 the code terminates during spike deconvolution. Here is the  error it gave me:
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\samih\Documents\suite2p7.0.3\suite2p\suite2p\__main__.py", line 62, in <module>
    parse_arguments()
  File "C:\Users\samih\Documents\suite2p7.0.3\suite2p\suite2p\__main__.py", line 55, in parse_arguments
    run_s2p.run_s2p(ops, db)
  File "C:\Users\samih\Documents\suite2p7.0.3\suite2p\suite2p\run_s2p.py", line 319, in run_s2p
>>>ERROR<<<
    'iscell': iscell})
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio.py", line 285, in savemat
    MW.put_variables(mdict)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 849, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 590, in write_top
    self.write(arr)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 619, in write
    self.write_struct(narr)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 738, in write_struct
    self._write_items(arr)
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 755, in _write_items
    self.write(el[f])
  File "C:\Users\samih\AppData\Local\Continuum\anaconda3\envs\suite2p\lib\site-packages\scipy\io\matlab\mio5.py", line 611, in write
>>>ERROR<<<
    % (arr, type(arr)))
TypeError: Could not convert 2020-05-19 05:03:07.872926 (type <class 'datetime.datetime'>) to array
Interrupted by error (not finished)

Thanks for having a look at it!

**Comment by carsen-stringer** [comment]
oops this isn't an error with spike deconvolution but with saving to mat actually, I took out the datetime object in ops before the matlab saving happens (it's used for the new NWB saving), it's correct in 0.7.4
