### ISSUE TITLE
Errors in running the Suite2p

### ISSUE THREAD

**Issue by Hanbing1999** [MouseLand/suite2p#406]
Good morning,

When , I found that when running the Suite2p and importing the data, Suite2p fails in opening the results. It turned out that there were a low of errors in the following lines. Could you please tell me how to deal with it? 

Thanks

>>>ERROR<<<
Traceback (most recent call last):
  File "D:\Python_install\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "D:\Python_install\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "D:\suite2p\suite2p-master\suite2p\__main__.py", line 63, in <module>
>>>ERROR<<<
    parse_arguments()
  File "D:\suite2p\suite2p-master\suite2p\__main__.py", line 57, in parse_arguments
>>>ERROR<<<
    suite2p.run_s2p(ops, db)
  File "D:\suite2p\suite2p-master\suite2p\run_s2p.py", line 223, in run_s2p
>>>ERROR<<<
    ops1 = io.tiff_to_binary(ops)
  File "D:\suite2p\suite2p-master\suite2p\io\tiff.py", line 162, in tiff_to_binary
>>>ERROR<<<
    im = imread(file, pages = range(ix, ix + nfr))
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 627, in imread
>>>ERROR<<<
    return tif.asarray(**kwargs)
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 2373, in asarray
>>>ERROR<<<
    result = stack_pages(pages, out=out, maxworkers=maxworkers)
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 11338, in stack_pages
>>>ERROR<<<
    func(page, i)
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 11333, in func
>>>ERROR<<<
    **kwargs)
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 5560, in asarray
>>>ERROR<<<
    return TiffPage.asarray(self, *args, **kwargs)
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 4736, in asarray
>>>ERROR<<<
    out=out
  File "D:\Python_install\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 6535, in read_array
>>>ERROR<<<
    n = fh.readinto(result)
PermissionError: [Errno 13] Permission denied
Interrupted by error (not finished)

**Comment by gg9761** [comment]
I believe I had a similar issue before - Are you running anaconda prompt in administrator mode? If not, try running as administrator to see if it fixes it.

**Comment by chriski777** [comment]
Did the suggestion above help fix it? I'm having trouble reproducing this error.

**Comment by chriski777** [comment]
Seems this has been fixed. Feel free to open/comment on it if this is still a problem.
