### ISSUE TITLE
error in ROI extraction

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#422]
The master branch currently fails:

Extracted fluorescence from 4254 ROIs in 7910 frames, 83.79 sec.
NOTE: applying classifier C:\Users\Marius\.suite2p\classifiers\classifier_user.npy
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\Marius\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\Marius\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Github\suite2p\suite2p\__main__.py", line 63, in <module>
>>>ERROR<<<
    parse_arguments()
  File "D:\Github\suite2p\suite2p\__main__.py", line 57, in parse_arguments
>>>ERROR<<<
    suite2p.run_s2p(ops, db)
  File "D:\Github\suite2p\suite2p\run_s2p.py", line 288, in run_s2p
>>>ERROR<<<
    ops1[ipl] = extraction.detect_and_extract(ops1[ipl])
  File "D:\Github\suite2p\suite2p\extraction\extract.py", line 215, in detect_and_extract
>>>ERROR<<<
    stat = stat[ic]
TypeError: only integer scalar arrays can be converted to a scalar index
Interrupted by error (not finished)

**Comment by marius10p** [comment]
Same error in the pip version.

**Comment by carsen-stringer** [comment]
fixed in master branch
