### ISSUE TITLE
Weird bug when number of frames = 1000

### ISSUE THREAD

**Issue by Vanwalleghem** [MouseLand/suite2p#449]
Hey Carsen,

I'm playing around with Suite2p with some artificial datasets (I'll send both of Marius and you an email about it later). There's a weird bug when the movies have a 1000 frames (same with one 3D tiff or 1000 2D tiffs) with this error : 
```----------- EXTRACTION
>>>ERROR<<<
Traceback (most recent call last):
  File "D:\Continuum\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "D:\Continuum\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "D:\tools\suite2p\suite2p\__main__.py", line 58, in <module>
    run_s2p(ops, db)
  File "D:\tools\suite2p\suite2p\run_s2p.py", line 353, in run_s2p
    op = run_plane(op, flag_binreg=flag_binreg)
  File "D:\tools\suite2p\suite2p\run_s2p.py", line 168, in run_plane
>>>ERROR<<<
    ops, stat = extraction.extract(ops, cell_pix, cell_masks, neuropil_masks, stat)
  File "D:\tools\suite2p\suite2p\extraction\extract.py", line 150, in extract
    F, Fneu, F_chan2, Fneu_chan2, ops = extract_traces_from_masks(ops, cell_masks, neuropil_masks)
  File "D:\tools\suite2p\suite2p\extraction\extract.py", line 120, in extract_traces_from_masks
>>>ERROR<<<
    F,Fneu,ops = extract_traces(ops, cell_masks, neuropil_masks, ops['reg_file'])
  File "D:\tools\suite2p\suite2p\extraction\extract.py", line 77, in extract_traces
    F[n,inds] = np.dot(data[:, cell_masks[n][0]], cell_masks[n][1])
IndexError: index 1000 is out of bounds for axis 1 with size 1000
Interrupted by error (not finished)
```
It does not happen if I remove 1 frame or add 1 frame, I suspect it's an issue with how the data is binned (I tried multiple batch_size and it didn't change the result).

I had a look in extract.py and added
```
        data = data[inds<nframes]
        inds = inds[inds<nframes]
```

before line 75
``` 
# extract traces and neuropil
for n in range(ncells):
            F[n,inds] = np.dot(data[:, cell_masks[n][0]], cell_masks[n][1])
```

this seemed to fix the issue

**Comment by carsen-stringer** [comment]
Hey Gilles I can't reproduce this with a 3D tiff, can you use the latest github version of the code? My test tiff is shape:
```
import tifffile

tif = tifffile.imread('D:/DATA/test/test.tif')
print(tif.shape)
```
(1000, 512, 512)

**Comment by Vanwalleghem** [comment]
Hey Carsen,

yep v0.8 did the trick, awesome, thanks!

BTW, I really love the GUI and amazing job with NMA (also congrats again!)
