### ISSUE TITLE
error in python3.7 suite2p environment on dev branch

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#472]
importlib_metadata needs to be added to setup.py please

Traceback (most recent call last):
  File "/groups/stringer/home/stringerc/anaconda4/envs/suite2p/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/groups/stringer/home/stringerc/anaconda4/envs/suite2p/lib/python3.7/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/groups/stringer/home/stringerc/anaconda4/envs/suite2p/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/groups/stringer/home/stringerc/github/suite2p/suite2p/__init__.py", line 1, in <module>
    from importlib_metadata import metadata as _metadata
ModuleNotFoundError: No module named 'importlib_metadata'

**Comment by chriski777** [comment]
I'm having trouble reproducing this with a fresh install. Is this occurring after you call `suite2p` in the CLI?

**Comment by nickdelgrosso** [comment]
Good catch, @carsen-stringer !  Added pull request.

**Comment by chriski777** [comment]
Fixed in #480, will close
