### ISSUE TITLE
Move minimize buttons to center

### ISSUE THREAD

**Issue by marius10p** [MouseLand/suite2p#50]
And change them to say cells not cells, and change color when pressed. Allow both to be pressed, but don't allow both to be unpressed.

**Comment by marius10p** [comment]
Error when pressing the buttons: 

===== 2018.08.16 12:08:24 =====
Traceback (most recent call last):
  File "D:\Github\suite2p\suite2p\gui2p.py", line 139, in <lambda>
    self.sizebtns.button(b).clicked.connect(lambda: self.view_size(b))
  File "D:\Github\suite2p\suite2p\gui2p.py", line 301, in view_size
    if self.minview[wplot].isChecked():
AttributeError: 'MainW' object has no attribute 'minview'
