### ISSUE TITLE
Error when using GUI for binning movie

### ISSUE THREAD

**Issue by yudl21132** [MouseLand/suite2p#542]
Hi, I have the following errors when Suite2p was binning the movie. I am a new user and not sure how to solve it. Hope to get some help from you. Thanks!  

Binning movie in chunks of length 21
Binned movie [2001,502,504], 47.76 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 398, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 218, in run_plane
    cell_pix, cell_masks, neuropil_masks, stat, ops = detection.detect(ops=ops, classfile=classfile)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/detection/detect.py", line 41, in detect
    ops=ops
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/detection/detect.py", line 80, in select_rois
    xrange=ops['xrange'],
  File "/home/anaconda3/envsbinyu/suite2p/lib/python3.7/site-packages/suite2p/detection/sparsedetect.py", line 316, in sparsery
    im, estimate_mode = find_best_scale(I=I, spatial_scale=spatial_scale)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/detection/sparsedetect.py", line 278, in find_best_scale
    return estimate_spatial_scale(I=I), EstimateMode.Estimated
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/detection/sparsedetect.py", line 266, in estimate_spatial_scale
    raise ValueError('ERROR: best scale was 0, everything should break now!')
ValueError: ERROR: best scale was 0, everything should break now!
Interrupted by error (not finished

**Comment by nickdelgrosso** [comment]
Hi @yudl21132 ,

Thank you for the report!  It looks like when suite2p analyzed your data and tried to estimate the best spatial_scale parameter value to do cell detection at, it ended up setting a value of 0, which wouldn't help it in the later analysis steps.  I'm not sure what aspects of the image affect this, but there is a solution to get around this problem: setting a spatial scale value yourself.

You can set a spatial scale value for suite2p to use by setting `spatial_scale` parameter to either 1, 2, 3, or 4.  Starting with it at 1 would be a good starting point.

Best wishes,

Nick

**Comment by yudl21132** [comment]
That works! Thank you so much, Nick!
