### ISSUE TITLE
Unable to load previously saved NWB file

### ISSUE THREAD

**Issue by kir0ul** [MouseLand/suite2p#544]
Hi,

It seems I'm not able to load back an NWB file I just created by running Suite2p.
I get the following traceback:
```
/home/apierre/Dev/calcium-imaging/Data/4new/save_path/suite2p/ophys.nwb
Traceback (most recent call last):
  File "/home/apierre/Dev/calcium-imaging/suite2p/suite2p/gui/menus.py", line 24, in <lambda>
    loadNWB.triggered.connect(lambda: io.load_dialog_NWB(parent))
  File "/home/apierre/Dev/calcium-imaging/suite2p/suite2p/gui/io.py", line 187, in load_dialog_NWB
    load_NWB(parent)
  File "/home/apierre/Dev/calcium-imaging/suite2p/suite2p/gui/io.py", line 208, in load_NWB
    load_to_GUI(parent, os.path.split(name)[0], procs)
  File "/home/apierre/Dev/calcium-imaging/suite2p/suite2p/gui/io.py", line 310, in load_to_GUI
    stat, ops, Fcell, Fneu, Spks, iscell, probcell, redcell, probredcell, hasred = procs
ValueError: not enough values to unpack (expected 10, got 9)
```
Let me know if you need more information.
Thanks!

**Comment by carsen-stringer** [comment]
this should work in v0.9.2? it's at least fixed in the github version (https://github.com/MouseLand/suite2p/blob/0858b6ba131105210f60277d05df120a5970d9df/suite2p/gui/io.py#L205)

**Comment by kir0ul** [comment]
My bad, I thought I was up to date but I was tracking the `master` branch, not the `main` branch  :grimacing:
