### ISSUE TITLE
Error when converting to binary

### ISSUE THREAD

**Issue by yudl21132** [MouseLand/suite2p#553]
Hi, I have the following error after running the suite2p. The error message doesn't give me any hints about how to debug it. If possible, I hope to get some suggestions from you. Thank you very much.

** Found 100 tifs - converting to binary **
2000 frames of binary, time 4.71 sec.
4000 frames of binary, time 8.70 sec.
6000 frames of binary, time 12.70 sec.
8000 frames of binary, time 16.70 sec.
10000 frames of binary, time 20.69 sec.
12000 frames of binary, time 24.70 sec.
14000 frames of binary, time 28.72 sec.
16000 frames of binary, time 32.76 sec.
18000 frames of binary, time 36.82 sec.
20000 frames of binary, time 40.84 sec.
22000 frames of binary, time 44.87 sec.
24000 frames of binary, time 48.90 sec.
26000 frames of binary, time 52.93 sec.
28000 frames of binary, time 56.97 sec.
30000 frames of binary, time 61.01 sec.
32000 frames of binary, time 65.03 sec.
34000 frames of binary, time 69.03 sec.
36000 frames of binary, time 73.02 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 377, in run_s2p
    ops0 = io.tiff_to_binary(ops.copy())
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/io/tiff.py", line 122, in tiff_to_binary
    im = tif.data(beg=ix, end=ix+nfr)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/ScanImageTiffReader/__init__.py", line 309, in data
    raise Exception(self.__ctx.log.decode("utf-8","strict"))
Exception: Resource temporarily unavailable
Interrupted by error (not finished)

**Comment by yudl21132** [comment]
This issue didn't happen for all of the cases. I am really not sure what the reason is. When I am running for another image set, I have this again. 

** Found 100 tifs - converting to binary **
2000 frames of binary, time 4.75 sec.
4000 frames of binary, time 8.79 sec.
6000 frames of binary, time 12.82 sec.
8000 frames of binary, time 16.86 sec.
10000 frames of binary, time 20.91 sec.
12000 frames of binary, time 24.95 sec.
14000 frames of binary, time 28.99 sec.
16000 frames of binary, time 33.02 sec.
18000 frames of binary, time 37.09 sec.
20000 frames of binary, time 41.12 sec.
22000 frames of binary, time 45.19 sec.
24000 frames of binary, time 49.66 sec.
26000 frames of binary, time 54.20 sec.
28000 frames of binary, time 58.78 sec.
30000 frames of binary, time 63.39 sec.
32000 frames of binary, time 68.02 sec.
34000 frames of binary, time 72.69 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 377, in run_s2p
    ops0 = io.tiff_to_binary(ops.copy())
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/io/tiff.py", line 122, in tiff_to_binary
    im = tif.data(beg=ix, end=ix+nfr)
  File "/home/anaconda3/envs/suite2p/lib/python3.7/site-packages/ScanImageTiffReader/__init__.py", line 309, in data
    raise Exception(self.__ctx.log.decode("utf-8","strict"))
Exception: Resource temporarily unavailable
Interrupted by error (not finished)


I also checked the machine's memory, and it seems ok. I really don't know what the problem is.

**Comment by carsen-stringer** [comment]
Are you able to load the last tiff into ImageJ? It could be corrupted somehow or not have finished writing?

**Comment by yudl21132** [comment]
Yes, I can load it into ImageJ.

**Comment by yudl21132** [comment]
It stopped at different time points for different runs. For example, I tried to re-run suite2p, and it stopped at 24000 frames instead of 34000 frames.

**Comment by yudl21132** [comment]
Hi, the files are all local. I somehow changed the batch size from 400 to 300, and the problem was gone. Not sure whether I will have this later again. The system monitor didn't show the memory is overused, and the computer I am using has 64 G RAM, so I feel it should be fine for the big batch size. Thank you very much for the quick response.
