### ISSUE TITLE
Issue during Registration

### ISSUE THREAD

**Issue by MarColnaghi** [MouseLand/suite2p#573]
Hello!
Sorry to disturb.

I'm currently running (for my first time ever) suite2p, but I keep getting a problem during the registration (i think?) part.
Here's the log:

_----------- REGISTRATION
[...]
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 397, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 193, in run_plane
    ops = registration.get_pc_metrics(ops)
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\metrics.py", line 233, in get_pc_metrics
>>>ERROR<<<
    spatial_taper=ops['spatial_taper']
  File "C:\Users\marco.colnaghi\Anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\metrics.py", line 134, in pc_register
    bidiphase.shift(Img, bidiphase)
AttributeError: 'numpy.int64' object has no attribute 'shift'
Interrupted by error (not finished)_

Thanks in advance!
Great work on the toolbox!
Marco

**Comment by gg9761** [comment]
Hi Marco,

I had a similar issue with the registration failing. I tried skipping the 1P pre-reg and it seemed to process after that. Let me know if that works for you

best,

George

**Comment by carsen-stringer** [comment]
Sorry about the bug, I've fixed the dev branch and will make a new pip soon:
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```
