### ISSUE TITLE
Error in loading file

### ISSUE THREAD

**Issue by mcalta** [MouseLand/suite2p#580]
Hi all,

I have some problem loading a file and running suite2p, below the detail, could you please help me?

Thanks a lot

{'data_path': ['C:/Users/m.caltabellotta/Downloads'], 'subfolders': [], 'save_path0': 'C:/Users/xxxxxxxx', 'fast_disk': 'C:/Users/xxxxxxx', 'input_format': 'mesoscan'}
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 372, in run_s2p
>>>ERROR<<<
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 219, in mesoscan_to_binary
>>>ERROR<<<
    ops['lines'] = opsj['lines']
KeyError: 'lines'
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
are you using a mesoscope tiff? if so you need to first run our conversion script on your tiff header here (currently only implemented in matlab): https://github.com/MouseLand/suite2p/blob/main/helpers/mesoscope_json_from_scanimage.m

then you can load the saved `ops.json` in the GUI for processing

**Comment by carsen-stringer** [comment]
is this still an issue? closing for now due to inactivity
