### ISSUE TITLE
Error prior to registration

### ISSUE THREAD

**Issue by cfk56629** [MouseLand/suite2p#581]
I installed suite2p on a few computers in the same way, and it works on 2/3, but on one I am getting this error every time I start trying to process data, I'm not really sure where to start with this:

** Found 24000 tifs - converting to binary **
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 372, in run_s2p
>>>ERROR<<<
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\Users\runyan1\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 402, in ome_to_binary
>>>ERROR<<<
    ops1[ix]['meanImg'] += im
TypeError: Cannot cast ufunc add output from dtype('int32') to dtype('uint16') with casting rule 'same_kind'
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
hmm that's strange that it's computer specific, I've forced the type-casting to int16 in the bruker loading now, it's implemented in the dev branch

```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git checkout dev
python -m suite2p
```
