### ISSUE TITLE
Compatibility with latest version of scanbox data

### ISSUE THREAD

**Issue by ziyizhu1996** [MouseLand/suite2p#593]
Hello,

Thank you very much for including direct preprocessing from scabox data. However, we have recently run into this error: 

```
>>>ERROR<<<
Traceback (most recent call last):
File "c:\users\smoorec2\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
"__main__", mod_spec)
File "c:\users\smoorec2\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
exec(code, run_globals)
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\__main__.py", line 78, in <module>
main()
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
run_s2p(ops, db)
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\run_s2p.py", line 372, in run_s2p
ops0 = convert_funs[ops['input_format']](ops.copy())
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\io\sbx.py", line 117, in sbx_to_binary
tmpsbx = sbx_memmap(sbxlist[0])
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\io\sbx.py", line 60, in sbx_memmap
sbxshape,nplanes = sbx_get_shape(filename)
File "C:\Users\smoorec2\Documents\suite2p-main\suite2p\io\sbx.py", line 42, in sbx_get_shape
if not isinstance(info.otwave,int):
AttributeError: 'mat_struct' object has no attribute 'otwave'
Interrupted by error (not finished)
```

I am guessing this is because the parameter 'otwave' (the configuration of optotune lens, e.g. sawtooth) is removed in the latest scanbox '.mat' file. It would be nice to update the package to reflect this change.

Thank you very much!

Ziyi Zhu

**Comment by carsen-stringer** [comment]
Do you know what this is replaced with? We'd appreciate a pull request on
this because don't have scanbox files and aren't familiar with them. Thanks

**Comment by ziyizhu1996** [comment]
I can check new scanbox data configuration and create a pull request on this issue to fix it. Do you know how should I create a pull request (e.g. shall I create from the master branch?)

Here is a screen shot of what I see if I click 'pull request'. Do you know what I should do from there?

![image](https://user-images.githubusercontent.com/26942783/101806031-7599d300-3ae1-11eb-837d-6d102ef0feef.png)

**Comment by carsen-stringer** [comment]
sorry it's a little confusing, you need to create a fork of the suite2p `main` branch and then make your changes and submit a pull request with your fork, here are some instructions: https://jarv.is/notes/how-to-pull-request-fork-github/. Let me or @nickdelgrosso if any of this is confusing.

**Comment by orena1** [comment]
I had the same issue and created a pull request:
https://github.com/MouseLand/suite2p/pull/564
But (as mention in the pull request), data-loading using sbxreader is much better and handles all of the edge-cases.
