### ISSUE TITLE
Suite2p error

### ISSUE THREAD

**Issue by JaiSubKU** [MouseLand/suite2p#601]
Hi,

I am new to Suite2p. When I try to run it, I get the following error. Can you please let me know how I can fix it? Thanks for your help.

Traceback (most recent call last):
  File "c:\users\j375s395\anaconda3\lib\site-packages\suite2p\gui\rungui.py", line 378, in run_S2P
    self.add_ops()
  File "c:\users\j375s395\anaconda3\lib\site-packages\suite2p\gui\rungui.py", line 347, in add_ops
    np.save('ops%d.npy'%L, self.ops)
  File "<__array_function__ internals>", line 5, in save
  File "c:\users\j375s395\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 524, in save
    file_ctx = open(file, "wb")
PermissionError: [Errno 13] Permission denied: 'ops0.npy'

**Comment by JaiSubKU** [comment]
Nevermind, I figured it out. My installation step had an error.
