### ISSUE TITLE
Backward compatibility issue

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#602]
Trying to load processed files from June 2019 with the most recent version of suite2p and getting following error:

```
Traceback (most recent call last):
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\menus.py", line 19, in <lambda>
    loadProc.triggered.connect(lambda: io.load_dialog(parent))
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\io.py", line 174, in load_dialog
    load_proc(parent)
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\io.py", line 302, in load_proc
    load_to_GUI(parent, basename, output)
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\io.py", line 326, in load_to_GUI
    make_masks_and_enable_buttons(parent)
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\io.py", line 62, in make_masks_and_enable_buttons
    views.init_views(parent)
  File "c:\users\dr. siemens\downloads\suite2p\suite2p\gui\views.py", line 79, in init_views
    vcorr = parent.ops['Vcorr']
KeyError: 'Vcorr'
```

Any idea how to open these files without the need to revert to an old version of suite2p?

**Comment by carsen-stringer** [comment]
not sure which version lacked Vcorr, but I've allowed for the Vcorr key to be absent from ops in loading
