### ISSUE TITLE
crash when attempting to open image

### ISSUE THREAD

**Issue by jackwalleninstituteorg** [MouseLand/suite2p#603]
I have a freshly installed version suite2p. I select a tiff or HDF5 movie to analyze via the GUI ('File > run suite2p'), click the 'run suite2p' button and a pop-up window appears with 'Python as stopped working. A problem caused the program to stop working correctly. Please close the program.' Closing the pop-up window closes suite2P.

The traceback in the conda window reads:

(base) C:\>python -m suite2p
loaded default ops
Traceback (most recent call last):
  File "C:\Users\jackw\AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\gui\rungui.py", line 378, in run_S2P
    self.add_ops()
  File "C:\Users\jackw\AppData\Local\Continuum\anaconda3\lib\site-packages\suite2p\gui\rungui.py", line 347, in add_ops
    np.save('ops%d.npy'%L, self.ops)
  File "<__array_function__ internals>", line 6, in save
  File "C:\Users\jackw\AppData\Local\Continuum\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 530, in save
    fid = open(file, "wb")
PermissionError: [Errno 13] Permission denied: 'ops0.npy'

**Comment by jackwalleninstituteorg** [comment]
Fixed by changing directory before opening suite2p form the conda prompt. I think maybe suite2p lacked write permission for the default directory?
