### ISSUE TITLE
Merged ROIs not saved

### ISSUE THREAD

**Issue by amdemchuk** [MouseLand/suite2p#618]
Hi,

When using Alt+Enter to merge two ROIs together, the ROIs are successfully merged but they are NOT saved as one merged ROI. When the file is closed and reopened in the Suite2P GUI, the two ROIs appear unmerged again. Help?!

Thank you!

**Comment by carsen-stringer** [comment]
sorry this isn't clear, in the top window, you have to click the save button to append them:
![image](https://user-images.githubusercontent.com/15067541/108295027-f79f1b80-7164-11eb-86ac-81be4d17023c.png)

**Comment by amdemchuk** [comment]
I'm so sorry - I wasn't entirely clear. I actually HAD tried to append the merges as you suggested but, whenever I did so, it would give me an error like this:

Traceback (most recent call last):
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\menus.py", line 19, in <lambda>
    loadProc.triggered.connect(lambda: io.load_dialog(parent))
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 174, in load_dialog
    load_proc(parent)
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 302, in load_proc
    load_to_GUI(parent, basename, output)
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 326, in load_to_GUI
    make_masks_and_enable_buttons(parent)
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\io.py", line 79, in make_masks_and_enable_buttons
    masks.init_masks(parent)
  File "c:\users\a.demchuk\appdata\local\continuum\miniconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 232, in init_masks
    i = int(1-iscell[n])
IndexError: index 1033 is out of bounds for axis 0 with size 1033

I tried this a few times on two different files and I always got this result. Furthermore, I couldn't open the files in the GUI at all after appending the merges. So I had (incorrectly) assumed that this "append merges" tab wasn't actually designed for ROIs merged with Alt-Enter.

**Comment by carsen-stringer** [comment]
oops found the bug, it was erroring during saving if you didn't have a second channel and then not saving the new iscell. I think that's your problem, let me know if this fix doesn't work
