### ISSUE TITLE
ValueError: bad marshal data

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#632]
On ubuntu 20.04, I followed instruction at https://github.com/MouseLand/suite2p#installation-of-github-version-for-developers, but am seeing the following error. `dvc` downloaded data successfully. Let me know how I can help troubleshoot? thank you!
```
❯ python setup.py test
running pytest
Searching for sbxreader
Best match: sbxreader 0.1.5
Processing sbxreader-0.1.5-py3.8.egg

Using /home/tyler/code/suite2p/.eggs/sbxreader-0.1.5-py3.8.egg
Searching for paramiko
Best match: paramiko 2.7.2
Processing paramiko-2.7.2-py3.8.egg

Using /home/tyler/code/suite2p/.eggs/paramiko-2.7.2-py3.8.egg
Searching for pyqtgraph
Best match: pyqtgraph 0.11.1
Processing pyqtgraph-0.11.1-py3.8.egg

Using /home/tyler/code/suite2p/.eggs/pyqtgraph-0.11.1-py3.8.egg
Searching for scanimage-tiff-reader>=1.4.1
Reading https://pypi.org/simple/scanimage-tiff-reader/
Downloading https://files.pythonhosted.org/packages/f4/1e/f3470cef5061beb800dd14c60241e8724504677ea24e9d77d01e1b123713/scanimage-tiff-reader-1.4.1.tar.gz#sha256=139b3001bc10ea736b6e8773e5db3a630cae7c254a872070a1184d0c2a4c5053
Best match: scanimage-tiff-reader 1.4.1
Processing scanimage-tiff-reader-1.4.1.tar.gz
Writing /tmp/easy_install-b84tbjv5/scanimage-tiff-reader-1.4.1/setup.cfg
Running scanimage-tiff-reader-1.4.1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-b84tbjv5/scanimage-tiff-reader-1.4.1/egg-dist-tmp-1c1l2nvl
warning: no previously-included files matching '*.h' found anywhere in distribution
warning: no previously-included files matching '*.a' found anywhere in distribution
warning: no previously-included files matching '*.lib' found anywhere in distribution
warning: no previously-included files matching 'src/**/external/**/bin/*' found anywhere in distribution
zip_safe flag not set; analyzing archive contents...
Traceback (most recent call last):
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-b84tbjv5/scanimage-tiff-reader-1.4.1/setup.py", line 18, in <module>
    ],
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 215, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 268, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 384, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 421, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    setuptools.setup(
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tyler/code/suite2p/.eggs/pytest_runner-5.3.0-py3.8.egg/ptr.py", line 202, in run
    installed_dists = self.install_dists(dist)
  File "/home/tyler/code/suite2p/.eggs/pytest_runner-5.3.0-py3.8.egg/ptr.py", line 153, in install_dists
    orig.test.install_dists(dist), self.install_extra_dists(dist)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/test.py", line 203, in install_dists
    ir_d = dist.fetch_build_eggs(dist.install_requires)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/dist.py", line 673, in fetch_build_eggs
    resolved_dists = pkg_resources.working_set.resolve(
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 764, in resolve
    dist = best[req.key] = env.best_match(
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1049, in best_match
    return self.obtain(req, installer)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1061, in obtain
    return installer(requirement)
  File "/home/tyler/code/suite2p/.eggs/pytest_runner-5.3.0-py3.8.egg/ptr.py", line 84, in fetch_build_egg
    return cmd.easy_install(req)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 669, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 695, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 880, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1150, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1134, in run_setup
    run_setup(setup_script, args)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 257, in run_setup
    raise
  File "/home/tyler/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/tyler/opt/anaconda3/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 139, in resume
    raise exc.with_traceback(self._tb)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 254, in run_setup
    _execfile(setup_script, ns)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/sandbox.py", line 43, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-b84tbjv5/scanimage-tiff-reader-1.4.1/setup.py", line 18, in <module>
    ],
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/tyler/opt/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 215, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 268, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 384, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/home/tyler/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 421, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)
```

**Comment by carsen-stringer** [comment]
weird, I'd recommend try python<3.8. You may want to post this as an issue for scanimagetiffreader: https://gitlab.com/vidriotech/scanimage-tiff-reader/-/issues
