### ISSUE TITLE
Error when saving large .mat file

### ISSUE THREAD

**Issue by bumoritz** [MouseLand/suite2p#638]
Hi,

Thanks for creating this awesome tool!

I'm trying to process some very long recordings (e.g., 479939 frames with 2996 ROIs detected). Suite2p runs fine on them and the npy files are saved out correctly. However, when trying to save out the Matlab file (either during the main suite2p run, or when importing the stat.npy into the GUI and pressing the Save to mat file button), suite2p throws the below error.

I don't think I'm running out of RAM as my computer has 64 GB. I suspect it either has something to do with limitations of the .mat format or the way scipy writes the file, and it seems like a similar problem has been raised on the scipy github site: https://github.com/scipy/scipy/issues/12465.

Is there anything we can do about it such that it's possible to save out these big Matlab files?

Thanks a lot in advance for your help!

`saving to mat
Traceback (most recent call last):
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\suite2p\gui\menus.py", line 45, in <lambda>
    parent.saveMat.triggered.connect(lambda: io.save_mat(parent))
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\suite2p\gui\io.py", line 415, in save_mat
    np.expand_dims(parent.probredcell,axis=1)), axis=1)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio.py", line 298, in savemat
    MW.put_variables(mdict)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 893, in put_variables
    self._matrix_writer.write_top(var, asbytes(name), is_global)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 634, in write_top
    self.write(arr)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 673, in write
    self.write_numeric(narr)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 699, in write_numeric
    self.write_element(arr)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 540, in write_element
    self.write_regular_element(arr, mdtype, byte_count)
  File "C:\Users\Moritz\Anaconda3\envs\suite2p_tif\lib\site-packages\scipy\io\matlab\mio5.py", line 554, in write_regular_element
    tag['byte_count'] = byte_count
OverflowError: Python int too large to convert to C long`

![Error](https://user-images.githubusercontent.com/56551968/110979763-f07ebe00-835c-11eb-9b2c-41919e2d23cc.PNG)

**Comment by orena1** [comment]
I did not find a way to solve it, indeed seems like a limitation of scipy.io
But I can suggest you save it as npy and load the npy file to MatLab using this:
https://github.com/kwikteam/npy-matlab

**Comment by bumoritz** [comment]
Thanks a lot for looking into it! And thanks for pointing me to this npy loading utility, that will solve it for me :)
