### ISSUE TITLE
multiple hdf5 files: missing frames

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#654]
I have 5 hdf5 files with a dataset named `data` and of the following shapes (TZHW):
```
1803 x 5 x 1024 x 1024
7272 x 5 x 1024 x 1024
1803 x 5 x 1024 x 1024
7272 x 5 x 1024 x 1024
1803 x 5 x 1024 x 1024
```

I specify the 5 folders containing one hdf5 file each, but suite2p outputs that it only `Wrote 9978 frames per binary for 5 planes` when it should write 19953 frames per binary for 5 planes. 

<details>
 <summary>suite2p output including error</summary>

```
{'data_path': ['/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-pre-037/hdf5/data', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-lrhab_raphe_stim-40trial-038/hdf5/data', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-mid-039/hdf5/data', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries_lrhab_raphe_40trial_part_2-040/hdf5/data', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries_resting_post-041/hdf5/data'], 'subfolders': [], 'h5py_key': 'data', 'save_path0': '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-pre-037/hdf5/data', 'fast_disk': '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-pre-037/hdf5/data', 'input_format': 'h5'}
h5
** Found 5 h5 files - converting to binary **
NOTE: using a list of h5 files:
['/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-pre-037/hdf5/data/data.h5', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-lrhab_raphe_stim-40trial-038/hdf5/data/data.h5', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries-resting-mid-039/hdf5/data/data.h5', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries_lrhab_raphe_40trial_part_2-040/hdf5/data/data.h5', '/data/dlab/b115/process-output/2020-10-28_elavl3-chrmine-Kv2.1_h2b6s_8dpf/fish1/TSeries_resting_post-041/hdf5/data/data.h5']
time 1172.36 sec. Wrote 9978 frames per binary for 5 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 9978 frames
Reference frame, 82.30 sec.
Registered 2000/9978 in 211.26s
Registered 4000/9978 in 422.34s
Registered 6000/9978 in 632.99s
Registered 8000/9978 in 843.02s
Registered 9978/9978 in 1051.19s
Registered second channel in 161.19 sec.
added enhanced mean image
----------- Total 1333.08 sec
Registration metrics, 60.49 sec.
NOTE: applying default /home/tyler/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 88
Binned movie [95,1016,1016] in 53.83 sec.
NOTE: estimated spatial scale ~6 pixels, time epochs 1.00, threshold 5.00 
0 ROIs, score=81.73
1000 ROIs, score=21.11
2000 ROIs, score=13.02
3000 ROIs, score=10.57
4000 ROIs, score=9.76
Detected 5000 ROIs, 32.55 sec
After removing overlaps, 4771 ROIs remain
>>>> CELLPOSE estimating masks in anatomical channel
ERROR importing or running cellpose, continuing without anatomical estimates
----------- Total 127.53 sec.
----------- EXTRACTION
Masks created, 1.37 sec.
Extracted fluorescence from 4771 ROIs in 9978 frames, 44.86 sec.
Extracted fluorescence from 4771 ROIs in 9978 frames, 48.34 sec.
----------- Total 95.89 sec.
----------- CLASSIFICATION
['npix_norm', 'skew', 'compact']
----------- Total 0.05 sec.
WARNING: skipping spike detection (ops['spikedetect']=False)
Plane 0 processed in 1617.39 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 1 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 9978 frames
Reference frame, 76.33 sec.
Registered 2000/9978 in 211.19s
Registered 4000/9978 in 421.67s
Registered 6000/9978 in 632.52s
Registered 8000/9978 in 844.76s
Registered 9978/9978 in 1053.99s
Registered second channel in 160.78 sec.
added enhanced mean image
----------- Total 1333.92 sec
Registration metrics, 61.30 sec.
NOTE: applying default /home/tyler/.suite2p/classifiers/classifier_user.npy
----------- ROI DETECTION
Binning movie in chunks of length 88
Binned movie [95,1016,1012] in 53.40 sec.
NOTE: estimated spatial scale ~6 pixels, time epochs 1.00, threshold 5.00 
0 ROIs, score=135.92
1000 ROIs, score=30.10
2000 ROIs, score=20.81
3000 ROIs, score=14.34
4000 ROIs, score=11.00
Detected 5000 ROIs, 38.12 sec
After removing overlaps, 4359 ROIs remain
>>>> CELLPOSE estimating masks in anatomical channel
ERROR importing or running cellpose, continuing without anatomical estimates
----------- Total 127.45 sec.
----------- EXTRACTION
Masks created, 2.08 sec.
Extracted fluorescence from 4359 ROIs in 9978 frames, 33.35 sec.
Extracted fluorescence from 4359 ROIs in 9978 frames, 33.24 sec.
----------- Total 69.97 sec.
----------- CLASSIFICATION
['npix_norm', 'skew', 'compact']
----------- Total 0.04 sec.
WARNING: skipping spike detection (ops['spikedetect']=False)
Plane 1 processed in 1593.00 sec (can open in GUI).
>>>>>>>>>>>>>>>>>>>>> PLANE 2 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 9975 frames
Reference frame, 75.74 sec.
Registered 2000/9975 in 210.96s
Registered 4000/9975 in 419.75s
Registered 6000/9975 in 629.11s
Registered 8000/9975 in 838.36s
Registered 9975/9975 in 1044.89s
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/tyler/opt/anaconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "/home/tyler/opt/anaconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tyler/code/suite2p/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/tyler/code/suite2p/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/tyler/code/suite2p/suite2p/run_s2p.py", line 428, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/home/tyler/code/suite2p/suite2p/run_s2p.py", line 196, in run_plane
    ops = registration.register_binary(ops, refImg=refImg) # register binary
  File "/home/tyler/code/suite2p/suite2p/registration/register.py", line 424, in register_binary
    yoff, xoff = ops['yoff'][iframes].astype(int), ops['xoff'][iframes].astype(int)
IndexError: index 9975 is out of bounds for axis 0 with size 9975
Interrupted by error (not finished)
```
</details>

Curiously, plane 2 inextricably gives an IndexError. Any ideas what may be going on? Happy to help troubleshoot & any tips of where to look appreciated! Thank you

**Comment by carsen-stringer** [comment]
here is where the h5 code is read in: https://github.com/MouseLand/suite2p/blob/4b6c3a95b53e5581dbab1feb26d67878db866068/suite2p/io/h5.py#L71 

it would be amazing if you could troubleshoot this, does it think you have two channels for some reason? that would be a reason to have half the frames?

**Comment by tbenst** [comment]
yes, oops! I specified 2 channels in ops by mistake.
