### ISSUE TITLE
cannot import name 'sip' from 'PyQt5'

### ISSUE THREAD

**Issue by djkapner** [MouseLand/suite2p#656]
I just started receiving these errors on an automated build/test (v0.9.3).

Solution:
`pip install pyqt5` after creating the conda environment from `environment.yml` 
or, possibly, move the pyqt requirement in `environment.yml`into the pip section to get a more recent version.

NOTE: I am not using the GUI, so, I can't speak to the needs of 1 particular pyqt version over another.

```
Traceback (most recent call last):
  File "/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/envs/suite2p/lib/python3.7/site-packages/ophys_etl/modules/suite2p_wrapper/__main__.py", line 8, in <module>
    import suite2p
  File "/envs/suite2p/lib/python3.7/site-packages/suite2p/__init__.py", line 3, in <module>
    from .gui import run as run_gui
  File "/envs/suite2p/lib/python3.7/site-packages/suite2p/gui/__init__.py", line 1, in <module>
    from .gui2p import run
  File "/envs/suite2p/lib/python3.7/site-packages/suite2p/gui/gui2p.py", line 8, in <module>
    import pyqtgraph as pg
  File "/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "/envs/suite2p/lib/python3.7/site-packages/pyqtgraph/Qt.py", line 137, in <module>
    from PyQt5 import QtGui, QtCore, QtWidgets, sip, uic
ImportError: cannot import name 'sip' from 'PyQt5' (/envs/suite2p/lib/python3.7/site-packages/PyQt5/__init__.py)
```

**Comment by carsen-stringer** [comment]
thanks done!
