### ISSUE TITLE
Registration fails

### ISSUE THREAD

**Issue by immj22** [MouseLand/suite2p#657]
Hello, I'm trying to use sutie2p for my two-photon imaging data analysis.
When I run the program, I have the below errors and cannot have any results in further.
I tried it with the sample tif files from your webpage but I still had the same errors. Can you help to sovle this issues please?
Thanks.

** Found 1 tifs - converting to binary **
2000 frames of binary, time 27.56 sec.
4000 frames of binary, time 41.39 sec.
time 44.81 sec. Wrote 4500 frames per binary for 1 planes>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 4500 frames
ERROR<<<
Traceback (most recent call last):
  File "c:\users\minju\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
ERROR<<<
    return _run_code(code, main_globals, None,
  File "c:\users\minju\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
ERROR<<<
    main()
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 428, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 196, in run_plane
    ops = registration.register_binary(ops, refImg=refImg) # register binary
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py", line 361, in register_binary
ERROR<<<
    refImg = compute_reference(ops, frames)
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\register.py", line 135, in compute_reference
    cfRefImg=rigid.phasecorr_reference(
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\rigid.py", line 60, in phasecorr_reference
ERROR<<<
    cfRefImg = complex_fft2(img=refImg, pad_fft=pad_fft)
  File "c:\users\minju\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\utils.py", line 222, in complex_fft2
    return np.conj(fft2(img, (next_fast_len(Ly), next_fast_len(Lx)))) if pad_fft else np.conj(fft2(img))
  File "mkl_fft\_pydfti.pyx", line 1097, in mkl_fft._pydfti.fft2
ERROR<<<
  File "mkl_fft\_pydfti.pyx", line 1083, in mkl_fft._pydfti._fftnd_impl
ERROR<<<
  File "mkl_fft\_pydfti.pyx", line 952, in mkl_fft._pydfti.iter_complementary
ERROR<<<
  File "mkl_fft\_pydfti.pyx", line 985, in mkl_fft._pydfti._direct_fftnd
ERROR<<<
AssertionError
Interrupted by error (not finished)

**Comment by FishQian** [comment]
I have a similar but different issue during registration

** Found 66 tifs - converting to binary **
time 69.81 sec. Wrote 26801 frames per binary for 1 planes
> PLANE 0 <
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 26801 frames
>>>ERROR<<<
Traceback (most recent call last):
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 398, in run_s2p
>>>ERROR<<<
    op = run_plane(op, ops_path=ops_path)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 177, in run_plane
    ops = registration.register_binary(ops) # register binary
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/register.py", line 207, in register_binary
    refImg = compute_reference(ops, frames)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/register.py", line 124, in compute_reference
    pad_fft=ops['pad_fft'],
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/rigid.py", line 35, in phasecorr_reference
    cfRefImg = complex_fft2(img=refImg, pad_fft=pad_fft)
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/registration/utils.py", line 107, in complex_fft2
    return np.conj(fft2(img, (next_fast_len(Ly), next_fast_len(Lx)))) if pad_fft else np.conj(fft2(img))
NameError: name 'fft2' is not defined
Interrupted by error (not finished)

**Comment by FishQian** [comment]
Hey I had some similar issues at the beginning but was resolved by following the git-clone envieonment.yml approach as in the [documentation](https://suite2p.readthedocs.io/en/latest/installation.html)
This way the version of dependencies will be limited.

then 
`conda activate suite2p
pip install pyqt5 --upgrade`
The GUI now can be launched after simply

`suite2p`
hope this helped.

**Comment by immj22** [comment]
Oh yes it's working now after I tried as your suggestion. Thanks for your help!
