### ISSUE TITLE
Registration Error: [ufunc 'apply_dotnorm' not supported for the input types]

### ISSUE THREAD

**Issue by FishQian** [MouseLand/suite2p#658]
Recently I tried to install suite2p but consistently found this error during registration: (see error message at the bottom)
1) I tested with different ways of installation combination:
           exactly follow the instructions @github or [the documentation ](https://suite2p.readthedocs.io/en/latest/installation.html#)
           Conda create suite2p env, then pip install suite2p
           newest 0.10.0 version of suite2p or force the version as 0.9.0/0.9.3. The same errors pop out as the same.
2) I tested with old dataset, which worked fine with previous version of suite2p, the error is there still
3) also multiple versions of Python for the env has been tested, including 3.7.7, 3.8~, 3.9~. Same error.

Any thoughts why? I checked through the website, the error seems to come from numpy

PLANE 0 <<<
NOTE: not registered / registration forced with ops['do_registration']>1
(no previous offsets to delete)
----------- REGISTRATION
registering 26801 frames
ERROR<<<
Traceback (most recent call last):
File "/Users/fish/anaconda3/envs/suite2p/lib/python3.8/runpy.py", line 192, in _run_module_as_main
ERROR<<<
return _run_code(code, main_globals, None,
File "/Users/fish/anaconda3/envs/suite2p/lib/python3.8/runpy.py", line 85, in _run_code
exec(code, run_globals)
File "/Users/fish/suite2p/suite2p/main.py", line 78, in
ERROR<<<
main()
File "/Users/fish/suite2p/suite2p/main.py", line 71, in main
run_s2p(ops, db)
File "/Users/fish/suite2p/suite2p/run_s2p.py", line 428, in run_s2p
op = run_plane(op, ops_path=ops_path)
File "/Users/fish/suite2p/suite2p/run_s2p.py", line 196, in run_plane
ops = registration.register_binary(ops, refImg=refImg) # register binary
File "/Users/fish/suite2p/suite2p/registration/register.py", line 366, in register_binary
ERROR<<<
refImg = compute_reference(ops, frames)
File "/Users/fish/suite2p/suite2p/registration/register.py", line 132, in compute_reference
ymax, xmax, cmax = rigid.phasecorr(
File "/Users/fish/suite2p/suite2p/registration/rigid.py", line 89, in phasecorr
data = convolve(data, cfRefImg)
File "/Users/fish/suite2p/suite2p/registration/utils.py", line 205, in convolve
return ifft2(apply_dotnorm(fft2(mov), img))
**TypeError: ufunc 'apply_dotnorm' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''**
Interrupted by error (not finished)

**Comment by FishQian** [comment]
Recently, a new error consistently appears, similar to some other issues in the forum but slightly different.



FOUND BINARIES AND OPS IN ['/Volumes/FishSSD3/CA3/KQ106_210412/suite2p/plane0/ops.npy']
>>> PLANE 0 <<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
----------- REGISTRATION
registering 26801 frames
>>>ERROR<<<
Traceback (most recent call last):
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.8/runpy.py", line 192, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "/Users/fish/anaconda3/envs/suite2p/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fish/suite2p/suite2p/__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "/Users/fish/suite2p/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/Users/fish/suite2p/suite2p/run_s2p.py", line 428, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/Users/fish/suite2p/suite2p/run_s2p.py", line 196, in run_plane
    ops = registration.register_binary(ops, refImg=refImg) # register binary
  File "/Users/fish/suite2p/suite2p/registration/register.py", line 366, in register_binary
>>>ERROR<<<
    refImg = compute_reference(ops, frames)
  File "/Users/fish/suite2p/suite2p/registration/register.py", line 132, in compute_reference
    ymax, xmax, cmax = rigid.phasecorr(
  File "/Users/fish/suite2p/suite2p/registration/rigid.py", line 89, in phasecorr
    data = convolve(data, cfRefImg)
  File "/Users/fish/suite2p/suite2p/registration/utils.py", line 205, in convolve
    return ifft2(apply_dotnorm(fft2(mov), img))
TypeError: ufunc 'apply_dotnorm' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Interrupted by error (not finished)

**Comment by FishQian** [comment]
@carsen-stringer

**Comment by FishQian** [comment]
https://suite2p.readthedocs.io/en/latest/installation.html

I solved this by git cloning the environment.yml to limit the dependencies as exact version.
Also I use the Mac Big Sur, so the GUI was not launched initially, but this is solved now thanks to the thread below

by 
```
conda activate suite2p
pip install pyqt5 --upgrade
```

#643
