### ISSUE TITLE
getting cell ordering from rastermap in visualization window/rastermap error

### ISSUE THREAD

**Issue by jyang-2** [MouseLand/suite2p#661]
Hi, thanks very much for this tool! 

I was wondering what the easiest way is to get the cell ordering for the rastermap in the visualization window of the gui. When I try to export as a csv/h5, it seems to create an empty file, and I get the following message in the anaconda prompt window: 

```
Traceback (most recent call last):
  File "c:\users\remy\anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\exporters\Exporter.py", line 77, in fileSaveFinished
    self.export(fileName=fileName, **self.fileDialog.opts)
  File "c:\users\remy\anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\exporters\CSVExporter.py", line 64, in export
    numRows = max([len(d[0]) for d in data])
ValueError: max() arg is an empty sequence
```

I've also tried running rastermap on it's own, after installing following directions on the 
rastermap/tutorial/ page, and I get the following error when I run the embedding algorithm:
>>>ERROR<<<
usage: __main__.py [-h] [--S S] [--ops OPS] [--iscell ISCELL]
__main__.py: error: unrecognized arguments: @ Caltech Dropbox/Remy/mb_odor_rearing/processed_data/2021-03-24/1/movie_001/suite2p/plane0/spks.npy @ Caltech Dropbox/Remy/mb_odor_rearing/processed_data/2021-03-24/1/movie_001/suite2p/plane0/iscell.npy
Interrupted by error (not finished)

Thanks again in advance!

**Comment by carsen-stringer** [comment]
you currently cannot export the ordering from the suite2p gui, I will add the enhancement tag

I think the problem you're running into with rastermap on the command line is that there are spaces in your file names, I think if you put them in " " quotes it will work
