### ISSUE TITLE
simple pip install requires qt, even if not using gui 

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/suite2p#665]
In integrating suite2p into a (batch) pipeline, one still needs to install qt -- even though I had no intention of running the gui.

```
pip install suite2p==0.10.0
python
>>> import suite2p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/croat/miniconda3/envs/two-photon/lib/python3.7/site-packages/suite2p/__init__.py", line 2, in <module>
    from .gui import run as run_gui
  File "/home/croat/miniconda3/envs/two-photon/lib/python3.7/site-packages/suite2p/gui/__init__.py", line 1, in <module>
    from .gui2p import run
  File "/home/croat/miniconda3/envs/two-photon/lib/python3.7/site-packages/suite2p/gui/gui2p.py", line 4, in <module>
    import pyqtgraph as pg
  File "/home/croat/miniconda3/envs/two-photon/lib/python3.7/site-packages/pyqtgraph/__init__.py", line 13, in <module>
    from .Qt import QtGui, mkQApp
  File "/home/croat/miniconda3/envs/two-photon/lib/python3.7/site-packages/pyqtgraph/Qt.py", line 50, in <module>
    raise Exception("PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.")
Exception: PyQtGraph requires one of PyQt5, PyQt6, PySide2 or PySide6; none of these packages could be imported.
```

**Comment by carsen-stringer** [comment]
this would require changing the setup.py and some of the imports, happy to take a pull request for this
