### ISSUE TITLE
GUI - Error while adding current data to classifier

### ISSUE THREAD

**Issue by LeonardoLupori** [MouseLand/suite2p#675]
Hey,
I'm getting an error when I try to update the default classifier with data from the current experiment.

I can replicate the error by clicking the *add current data to classifier* button in the GUI.

Hope this helps :)
If you need any more details just let me know

## My system
Windows 10
Suite2p  0.10.0 (installed in a conda virtual env)

## Error message
```
Adding current dataset to classifier
Traceback (most recent call last):
  File "c:\users\leonardo\.conda\envs\suite2p\lib\site-packages\suite2p\gui\classgui.py", line 23, in <lambda>
    parent.addtoclass.clicked.connect(lambda: add_to(parent))
  File "c:\users\leonardo\.conda\envs\suite2p\lib\site-packages\suite2p\gui\classgui.py", line 163, in add_to
    stats = np.reshape(np.array([parent.stat[j][k] for j in range(len(parent.stat)) for k in parent.model.keys]),
  File "c:\users\leonardo\.conda\envs\suite2p\lib\site-packages\suite2p\gui\classgui.py", line 163, in <listcomp>
    stats = np.reshape(np.array([parent.stat[j][k] for j in range(len(parent.stat)) for k in parent.model.keys]),
AttributeError: 'MainWindow' object has no attribute 'model'
```

**Comment by LeonardoLupori** [comment]
I solved the issue,

The *add current data to classifier* button is clickable even if there are no classifiers loaded and the GUI is thus showing probabilities from iscell.npy

In this situation, clicking the button to update a non-loaded classifier fails.
After loading a classifier (even the built-in one) the button works fine!
