### ISSUE TITLE
merge selected ROIs error

### ISSUE THREAD

**Issue by cgaletzka** [MouseLand/suite2p#700]
First of all, thank you for making this software freely available!

I am running suite2p on single-channel one-photon recordings. I receive two different error messages when trying to merge auto-suggested selected ROIs in the GUI.

---
creating merge window... this may take some time
computing automated merge suggestions...
merging activity... this may take some time
Traceback (most recent call last):
  File "c:\users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 209, in <lambda>
    self.doMerge.clicked.connect(lambda: self.do_merge(parent))
  File "c:\users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 249, in do_merge
    merge_activity_masks(parent)
  File "c:\users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 138, in merge_activity_masks
    np.delete(parent.F_chan2, k, 0)
AttributeError: 'MainWindow' object has no attribute 'F_chan2'
---

The other error happens whenever the cell index is higher than the number of classified cells. In the code below, the first two ROIs (8 and 11) are successfully merged. The second pair is not merged. I had classified 44 ROIs as cells at that point.

---
creating merge window... this may take some time
computing automated merge suggestions...
merging activity... this may take some time
ROIs merged: [ 8 11]
computing automated merge suggestions...
merging activity... this may take some time
Traceback (most recent call last):
  File "c:\users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 209, in <lambda>
    self.doMerge.clicked.connect(lambda: self.do_merge(parent))
  File "c:\users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\gui\merge.py", line 259, in do_merge
    self.CC[parent.imerge] = 0
IndexError: index 46 is out of bounds for axis 0 with size 44
---

Maybe I missed an important step. I appreciate any help with these issues!

**Comment by carsen-stringer** [comment]
I can't reproduce this error are you using the latest version?
`pip install suite2p --upgrade`

**Comment by cgaletzka** [comment]
Upgrading suite2p fixed the issue. I was using 0.10.0 instead of 0.10.1. Thank you!!
