### ISSUE TITLE
hdf5 format not clear

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#701]
Hello, I'm a bit unclear as to what array formats are supported by suite2p for hdf5. I have a (11444, 1, 10, 512, 512) size array in TCZHW, and I get the following error: `ValueError: cannot reshape array of size 131072000 into shape (500,10,512)`.

131072000 might be coming from 500\*512\*512...? That would make sense as my batch size is 500.

<details>

<summary>error output</summary>

```
{'data_path': ['/scratch/b115/2021-06-08_rsChRmine_h2b6s/fish2/s2p'], 'subfolders': [], 'h5py_key': '/imaging/PerVoxelLSTM_actually_shared-separate_bias_hidden-2021-06-21_6pm', 'save_path0': '/scratch/b115/2021-06-08_rsChRmine_h2b6s/fish2/s2p', 'fast_disk': '/scratch/b115/2021-06-08_rsChRmine_h2b6s/fish2/s2p', 'input_format': 'h5'}
h5
** Found 1 h5 files - converting to binary **
NOTE: using a list of h5 files:
['/scratch/b115/2021-06-08_rsChRmine_h2b6s/fish2/s2p/TSeries-lrhab-titration-1232021-06-21_6pm.ty.h5']
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 411, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/io/h5.py", line 67, in h5py_to_binary
    im = np.reshape(im, (im.shape[0]*nplanes,im.shape[2],im.shape[3]))
  File "<__array_function__ internals>", line 6, in reshape
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
>>>ERROR<<<
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 131072000 into shape (500,10,512)
Interrupted by error (not finished)
```

</details>

**Comment by tbenst** [comment]
In looking at the code, it seems 4-dim is assumed:
https://github.com/MouseLand/suite2p/blob/4b6c3a95b53e5581dbab1feb26d67878db866068/suite2p/io/h5.py#L46

And yet elsewhere the code attempts to be channel-aware:
https://github.com/MouseLand/suite2p/blob/4b6c3a95b53e5581dbab1feb26d67878db866068/suite2p/io/h5.py#L50
https://github.com/MouseLand/suite2p/blob/4b6c3a95b53e5581dbab1feb26d67878db866068/suite2p/io/h5.py#L75

It would seem that multiple channel support of hdf5 is intended but not implemented..?

**Comment by carsen-stringer** [comment]
the intention was to support interleaved data, I've updated it, can you try the github version now please? 
```
# if h5py data is 5D or 4D instead of 3D, assume that
# data = (nchan x) (nframes x) nplanes x pixels x pixels 
# 5D/4D data is flattened to process the same way as interleaved data
```

**Comment by carsen-stringer** [comment]
closing for now, let me know if it's not working
