### ISSUE TITLE
cannot serialize a bytes object larger than 4 GiB

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#702]
Unfortunately, `np.save` is not currently appropriate for large pickled files until https://github.com/numpy/numpy/issues/18784 is resolved. This can be fixed by instead using pickle4, e.g. `pickle.dump(array, fp, protocol=4)`. Although, I'm not sure why ops is >4GiB, that seems unexpected...?

```
----------- CLASSIFICATION
----------- Total 0.02 sec.
WARNING: skipping spike detection (ops['spikedetect']=False)
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tyler/code/suite2p/suite2p/__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "/home/tyler/code/suite2p/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/tyler/code/suite2p/suite2p/run_s2p.py", line 398, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/home/tyler/code/suite2p/suite2p/run_s2p.py", line 305, in run_plane
    np.save(ops['ops_path'], ops)
  File "<__array_function__ internals>", line 6, in save
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/numpy/lib/npyio.py", line 553, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/tyler/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/numpy/lib/format.py", line 676, in write_array
>>>ERROR<<<
    pickle.dump(array, fp, protocol=3, **pickle_kwargs)
OverflowError: cannot serialize a bytes object larger than 4 GiB
Interrupted by error (not finished)
```

**Comment by carsen-stringer** [comment]
yeah that's weird, can you try pickle dumping it and see what's so big please? I'd be more worried about stat being large
