### ISSUE TITLE
error after spike deconvolution

### ISSUE THREAD

**Issue by MelinaTimplalexi** [MouseLand/suite2p#706]
Hi, I am trying to run suite2p and I keep getting this error. I tried in other computers that I had previously installed it and I don't get this error with the same data. I assume I did something wrong in the installation process, I try to reinstall it but again I had the same. I can't fine where is the issue. 
---------- SPIKE DECONVOLUTION

----------- Total 1.50 sec.

>>>ERROR<<<
Traceback (most recent call last):

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main

>>>ERROR<<<
    return _run_code(code, main_globals, None,

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code

    exec(code, run_globals)

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>

    main()

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main

>>>ERROR<<<
    run_s2p(ops, db)

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 450, in run_s2p

    op = run_plane(op, ops_path=ops_path)

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 304, in run_plane

    ops_matlab['data_path'] = [os.fspath(p.absolute()) for p in ops_matlab['data_path']]

  File "C:\Users\Melina\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 304, in <listcomp>

    ops_matlab['data_path'] = [os.fspath(p.absolute()) for p in ops_matlab['data_path']]

AttributeError: 'str' object has no attribute 'absolute'

**Comment by carsen-stringer** [comment]
sorry about that, this is fixed now in the github version of the code, install using these instructions: https://github.com/MouseLand/suite2p#installing-the-latest-github-version-of-the-code

**Comment by MelinaTimplalexi** [comment]
that seems to have solved the problem! Thank you a lot!
