### ISSUE TITLE
OS Error Issue with New Install

### ISSUE THREAD

**Issue by borovij** [MouseLand/suite2p#707]
Hello,

I am attempting to install suite2p on a desktop in our lab, and the installation is fine until I try to run the command "python -m suite2p," at which point I am getting an error I am not familiar with, shown below: 
Has anyone experienced this error before or could anyone provide insight on how to resolve it? I have already tried uninstalling and reinstalling suite2p and making sure all dependencies are up to date, which I think they are. Thanks!

(suite2p) C:\Users\borovij\Desktop\suite2p>python -m suite2p
Traceback (most recent call last):
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\borovij\Desktop\suite2p\suite2p\__init__.py", line 1, in <module>
    from .run_s2p import run_s2p, default_ops
  File "C:\Users\borovij\Desktop\suite2p\suite2p\run_s2p.py", line 12, in <module>
    from . import extraction, io, registration, detection, classification
  File "C:\Users\borovij\Desktop\suite2p\suite2p\extraction\__init__.py", line 1, in <module>
    from .dcnv import preprocess, oasis
  File "C:\Users\borovij\Desktop\suite2p\suite2p\extraction\dcnv.py", line 2, in <module>
    from numba import njit, prange
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\site-packages\numba\__init__.py", line 19, in <module>
    from numba.core import config
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\site-packages\numba\core\config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "C:\Users\borovij\Anaconda3\envs\suite2p\lib\site-packages\llvmlite\binding\ffi.py", line 191, in <module>
    raise OSError("Could not load shared object file: {}".format(_lib_name))
OSError: Could not load shared object file: llvmlite.dll

(suite2p) C:\Users\borovij\Desktop\suite2p>

**Comment by carsen-stringer** [comment]
hmm I haven't seen that error before, can you try installing numba and llvmlite from the numba conda channel as follows:
```
conda install -c numba numba
conda install -c numba llvmlite
```

cc https://github.com/numba/llvmlite/issues/650#issuecomment-865287766

**Comment by borovij** [comment]
This worked, thank you so much!
