### ISSUE TITLE
KeyError: imerge and failed deconvolution when manual labeling

### ISSUE THREAD

**Issue by simo-91** [MouseLand/suite2p#712]
First of all, thank you immensely for this piece of software. I'm a big fan of all your work!

Disclaimer: I'm on macOS Catalina.
I'm experiencing this issue after selecting two ROIs for merging:
```
merging activity... this may take some time
Traceback (most recent call last):
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/gui2p.py", line 269, in keyPressEvent
    merge.do_merge(self)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/merge.py", line 31, in do_merge
    merge_activity_masks(parent)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/merge.py", line 58, in merge_activity_masks
    if len(parent.stat[n]['imerge']) > 0:
KeyError: 'imerge'
```

Moreover, when I manually add a ROI and extract it, I get this:
```
1 cells added to manual GUI
Masks made in 5.14 sec.
Extracted fluorescence from 1 ROIs in 600 frames, 4.48 sec.
Saving old stat
Num cells 1
Saving new stat
(1529, 600) (1529, 600) (1529, 600) (1529, 2) (1529,)
/Volumes/Seagate/880 NBTGCaMP6s_nacre--/25042021/25042021_NBTGCaMP6s_nacre__AKT1_lexOPRFP_5dpf/fish1/hindbrain/suite2p/plane0/stat.npy
no channel 2 labels found (redcell.npy)
0.14344191551208496
Traceback (most recent call last):
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/drawroi.py", line 276, in close_GUI
    io.load_proc(self.parent)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/io.py", line 303, in load_proc
    load_to_GUI(parent, basename, output)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/io.py", line 328, in load_to_GUI
    make_masks_and_enable_buttons(parent)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/io.py", line 102, in make_masks_and_enable_buttons
    parent.mode_change(2)
  File "/Users/Simo/opt/anaconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/gui2p.py", line 402, in mode_change
    nb = int(np.floor(float(self.Fcell.shape[1]) / float(self.bin)))
ZeroDivisionError: float division by zero
```
The ROI is created, but for some reason the deconvolved trace is a constant 0 (while the raw Fluorescence and neuropil are present)

Thank you!

**Comment by simo-91** [comment]
I solved the issues: the problem originated when allow_overlap is set to 0 (false). All good! 
Cheers
