### ISSUE TITLE
Error installing on Mac M1

### ISSUE THREAD

**Issue by frederikrogge** [MouseLand/suite2p#737]
I am having troubles installing the tool on MacBook Air M1 with Big Sur version 11.6. Apparently, the problem has to do with the installation of PyQt5. I get the following error message:

Pip subprocess error:
    ERROR: Command errored out with exit status 1:
     command: /Users/frederikrogge/miniforge3/envs/suite2p/bin/python /Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/tmp4q38hrcp
         cwd: /private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-install-8beq95o9/pyqt5_ab1921a7f82d4b129b46ff70f0fb5c61
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 349, in <module>
        main()
      File "/Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 331, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 147, in prepare_metadata_for_build_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 484, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-build-env-la5bkhpu/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8e/a4/d5e4bf99dd50134c88b95e926d7b81aad2473b47fde5e3e4eac2c69a8942/PyQt5-5.15.4.tar.gz#sha256=2a69597e0dd11caabe75fae133feca66387819fc9bc050f547e5551bce97e5be (from https://pypi.org/simple/pyqt5/) (requires-python:>=3.6). Command errored out with exit status 1: /Users/frederikrogge/miniforge3/envs/suite2p/bin/python /Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/tmp4q38hrcp Check the logs for full command output.
    ERROR: Command errored out with exit status 1:
     command: /Users/frederikrogge/miniforge3/envs/suite2p/bin/python /Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/tmpu5ejgae9
         cwd: /private/var/folders/mr/n5s35q7j47n7wf8c1z8zzv280000gn/T/pip-install-8beq95o9/pyqt5_28987973e1f14b9eaa736ac0979968d1
    Complete output (29 lines):
    Traceback (most recent call last):
      File "/Users/frederikrogge/miniforge3/envs/suite2p/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 143, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
...

Any suggestions on how to resolve this? I already tried to use a Rosetta-based terminal that would translate packages from the x86_64 environment, but this did not help. Thank you!

**Comment by carsen-stringer** [comment]
it appears you are using miniforge --- it may be better to use a full anaconda install to ensure that all the packages install correctly -- pyqt is a default package in anaconda. then you can pip install the other packages you need.

**Comment by carsen-stringer** [comment]
but I do not have a Mac to test, if you sort it out, I'm happy to take a pull request on the readme or the readthedocs so that your solutions can help other users :) cc @Gumphrey

**Comment by prajayshah** [comment]
i experienced issues as well installing on M1 Mac. I had to use the following steps: 

USE ROSETTA OPENED COPY OF TERMINAL (https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g)
`/usr/bin/python3 -m venv env`  - use non homebrew system installed version of python to create virtual environment
`source env/bin/activate`  - activate python virtual env
`pip install --upgrade pip`
`pip install PyQT5`
`python -m pip install wheel setuptools`
`pip install scanimage-tiff-reader`
`pip install suite2p`
`python -m suite2p`  - open suite2p GUI to confirm successful install. 

i was trying a bunch of things during the troubleshooting process, so somebody else should probably repeat these steps to ensure something isn't missing.

**Comment by simo-91** [comment]
I can run suite2p on my M1pro after full anaconda installation (using the last release -Universal). Unfortunately, it runs very slow because Rosetta has to translate everything, but that's expected. An average run takes me around 30min, while the same sample/setup runned on my other machine with Ubuntu 18.0 takes only a couple of minutes.

**Comment by carsen-stringer** [comment]
suite2p no longer has anaconda dependencies, perhaps this will make this easier on mac M1? would you like to make a pull request to our documentation with the details @prajayshah ?

**Comment by prajayshah** [comment]
sure, ive added this in: https://github.com/MouseLand/suite2p/pull/859#issue-1299460646
