### ISSUE TITLE
Zcorr error persists with updated Suite2p

### ISSUE THREAD

**Issue by marysethomas** [MouseLand/suite2p#756]
This is related to issue https://github.com/MouseLand/suite2p/issues/726

After pulling the latest github version, I get a new error when attempting to calculate Zcorr:

`
Traceback (most recent call last):
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 693, in go_to_frame
    self.jump_to_frame()
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 776, in jump_to_frame
    self.next_frame()
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 294, in next_frame
    [self.zmax[self.cframe],self.zmax[self.cframe]],
AttributeError: 'BinaryPlayer' object has no attribute 'zmax'
Traceback (most recent call last):
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 236, in add_zstack
    self.next_frame()
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 294, in next_frame
    [self.zmax[self.cframe],self.zmax[self.cframe]],
AttributeError: 'BinaryPlayer' object has no attribute 'zmax'
Traceback (most recent call last):
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 724, in <lambda>
    self.computeZ.clicked.connect(lambda: self.compute_z(parent))
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\gui\reggui.py", line 795, in compute_z
    ops, zcorr = registration.compute_zpos(self.zstack, self.ops[0])
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\registration\zalign.py", line 162, in compute_zpos
    cfRefImag = rigid.phasecorr_reference(
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\registration\rigid.py", line 62, in phasecorr_reference
    cfRefImg = complex_fft2(img=refImg)
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\registration\utils.py", line 251, in complex_fft2
    return np.conj(fft2(img, (next_fast_len(Ly), next_fast_len(Lx)))) if pad_fft else np.conj(fft2(img))
  File "C:\Users\MET74\Documents\GitHub\suite2p\suite2p\registration\utils.py", line 26, in fft2
    data_torch = torch.from_numpy(data)
TypeError: can't convert np.ndarray of type numpy.uint16. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint8, and bool.`

**Comment by carsen-stringer** [comment]
thanks, added the bug tag

**Comment by marysethomas** [comment]
@carsen-stringer I was able to fix this bug by adding Line 26: `data = data.astype(np.float32)` in registration\utils.py

Hope this helps!

Maryse
