### ISSUE TITLE
Numba Warning Message when Suite2p starts

### ISSUE THREAD

**Issue by jmdelahanty** [MouseLand/suite2p#804]
Hello! With our newly installed Suite2p instances on our cluster, we're running into a message that pops up when we start suite2p:

`Numba: Attempted to fork from a non-main thread, the TBB library may be in an invalid state in the child process.`

I'm wondering if this is an issue at all that we should worry about. I'll try `conda upgrade numba` and see if it does it... will report back

**Comment by jmdelahanty** [comment]
Interestingly while running something right now, I ran into this:

```
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/run_s2p.py", line 448, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/run_s2p.py", line 202, in run_plane
    ops = registration.register_binary(ops, refImg=refImg) # register binary
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/registration/register.py", line 388, in register_binary
>>>ERROR<<<
    frames, ymax, xmax, cmax, ymax1, xmax1, cmax1 = register_frames(refAndMasks, frames, ops)
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/registration/register.py", line 264, in register_frames
>>>ERROR<<<
    ymax1, xmax1, cmax1 = nonrigid.phasecorr(
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/registration/nonrigid.py", line 182, in phasecorr
>>>ERROR<<<
    Y = convolve(mov=Y, img=cfRefImg)
  File "/home/jdelahanty/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/registration/utils.py", line 234, in convolve
>>>ERROR<<<
    return ifft2(apply_dotnorm(fft2(mov), img)) #.astype(np.complex64)
KeyboardInterrupt
Interrupted by error (not finished)
```

I saw in #608 it could be related to `numba`

**Comment by jmdelahanty** [comment]
It doesn't appear that this causes any problems, we can run Suite2p without any issues as far as I can tell. So I'll close the issue now and update this thread if I run into a solution for that message later...
