### ISSUE TITLE
Error when loading z-stack tiff

### ISSUE THREAD

**Issue by mariacozan** [MouseLand/suite2p#811]
Hello! I have been trying to align my data to a Z-stack in the the GUI under "View Registered Binary->load z-stack tiff"
My data is 256x256 pixels and I have 8 planes (from 1 channel) spaced at 2um (2001 frames in total) . My z-stack has 101 planes also at 256x256 spaced at 1um with 10 frames/plane so 1010 frames. I have averaged this to have the shape (101,512,512) (so number of planes by number of pixels in Y by number of pixels in X)

This loaded the z stack on the right of my registered binary,
However, nothing is showing up in the third row as it should according to [this](https://suite2p.readthedocs.io/en/latest/gui.html?highlight=Z-alignment#z-stack-alignment) and in the Anaconda Prompt an error is appearing:
` Traceback (most recent call last):
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 693, in go_to_frame
    self.jump_to_frame()
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 776, in jump_to_frame
    self.next_frame()
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 294, in next_frame
    [self.zmax[self.cframe],self.zmax[self.cframe]],
AttributeError: 'BinaryPlayer' object has no attribute 'zmax'
Traceback (most recent call last):
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 236, in add_zstack
    self.next_frame()
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 294, in next_frame
    [self.zmax[self.cframe],self.zmax[self.cframe]],
AttributeError: 'BinaryPlayer' object has no attribute 'zmax'`

Here is how it looks like:
![image](https://user-images.githubusercontent.com/83554323/161312350-3ba57a53-b238-4375-b128-3c61d4a1cb74.png)

Then when I click on `compute z position`, this error appears:
`Traceback (most recent call last):
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 724, in <lambda>
    self.computeZ.clicked.connect(lambda: self.compute_z(parent))
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\reggui.py", line 795, in compute_z
    ops, zcorr = registration.compute_zpos(self.zstack, self.ops[0])
  File "C:\Users\maria\anaconda3\envs\suite2p\lib\site-packages\suite2p\registration\zalign.py", line 162, in compute_zpos
    cfRefImag = rigid.phasecorr_reference(
TypeError: phasecorr_reference() got an unexpected keyword argument 'pad_fft'`

Any idea what the issue might be?

 Thanks in advance for any help :)

**Comment by marysethomas** [comment]
Hi @mariacozan, please see these threads:
- https://github.com/MouseLand/suite2p/issues/726
- https://github.com/MouseLand/suite2p/issues/756

I had the same error as you which was resolved by an update from Carsen. Are you using the most recent Github version of Suite2p? Afterwards I had to make a small fix to resolve another bug, is described in the threads

**Comment by mariacozan** [comment]
Hi @marysethomas, thanks for the reply! I do have the most recent version and I already added the line of code you mentioned in the comment but it still gives me the same errors unfortunately.

**Comment by mariacozan** [comment]
Update: It works now, I was just using pip install to get the most recent version (which unfortunately is one version behind) instead of directly getting the most recent version from Github (0.10.3) (thanks @marysethomas for helping me get to the bottom of this!)

**Comment by marysethomas** [comment]
Great! You're very welcome!
