### ISSUE TITLE
[bug] tifffile.imread no longer supports pages parameter

### ISSUE THREAD

**Issue by CBroz1** [MouseLand/suite2p#831]
Problem: [tiffile documentation](https://github.com/cgohlke/tifffile/blob/master/tifffile/tifffile.py#L118l) states that the pages parameter was removed in 2022.4.22. 

Solution: Pin tifffile requirement to  < 2022.4.22 ?

**Comment by chriski777** [comment]
Thanks for letting us know about this issue, @CBroz1! We've updated our `imread` calls to now use the `key` params instead of the `pages`. I think that fixes this issue so I'll close it for now.

**Comment by AntoineMal** [comment]
Hello! 

I'm getting the same problem with the latest version of the GUI. 
I already make a post, but I though it was more appropriate to put it here too.

Best

Antoine
tif
** Found 1 tifs - converting to binary **
NOTE: ScanImageTiffReader not working for this tiff type, using tifffile

ERROR<<<
Traceback (most recent call last):
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
ERROR<<<
return run_code(code, main_globals, None,
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\runpy.py", line 87, in run_code
ERROR<<<
exec(code, run_globals)
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p_main.py", line 78, in
main()
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p_main.py", line 71, in main
run_s2p(ops, db)
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 394, in run_s2p
ops0 = io.tiff_to_binary(ops.copy())
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 148, in tiff_to_binary
im = imread(file, pages=range(ix, ix + nfr))
File "C:\Users\antoi\anaconda3\envs\suite2p\lib\site-packages\tifffile\tifffile.py", line 987, in imread
ERROR<<<
raise TypeError(
TypeError: imread() got unexpected keyword arguments 'pages'
Interrupted by error (not finished)
