### ISSUE TITLE
TypeError when running suite2p

### ISSUE THREAD

**Issue by saramoberg** [MouseLand/suite2p#850]
Hey Everyone and thanks for a great product! 

I recently upgraded suite2p because I could not install cellpose for some reason on my older version. Now, however I keep getting TypeErrors:

```
After removing overlaps, 19 ROIs remain
----------- Total 59.25 sec.
----------- EXTRACTION
Masks created, 0.48 sec.
>>>ERROR<<<
Traceback (most recent call last):
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 429, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 292, in run_plane
>>>ERROR<<<
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 138, in pipeline
    stat, F, Fneu, F_chan2, Fneu_chan2 = extraction.extraction_wrapper(stat, f_reg, f_reg_chan2=f_reg_chan2, ops=ops)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\extraction\extract.py", line 177, in extraction_wrapper
    F, Fneu = extract_traces(f_reg, cell_masks, neuropil_masks, batch_size=batch_size)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\extraction\extract.py", line 76, in extract_traces
    neuropil_npix = np.array([len(neuropil_ipixi) for neuropil_ipixi in neuropil_ipix]).astype(np.float32)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\extraction\extract.py", line 76, in <listcomp>
>>>ERROR<<<
    neuropil_npix = np.array([len(neuropil_ipixi) for neuropil_ipixi in neuropil_ipix]).astype(np.float32)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\numba\typed\typedlist.py", line 275, in __iter__
    yield self[i]
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\numba\typed\typedlist.py", line 271, in __getitem__
>>>ERROR<<<
    return _getitem(self, i)
TypeError: expected dtype object, got 'numpy.dtype[int64]'
Interrupted by error (not finished)
```

This error is new to me, where it's always worked out fine before. Now I'm using  v0.11.1.dev3+gaea0cde

Thanks for any help!

**Comment by saramoberg** [comment]
To add to this, I tried running with cellpose (which I didn't in the abovementioned post) and got a similar issue but with float:

```
>>>> CELLPOSE finding masks in mean_img
!NOTE! diameter set to 40.00 for cell detection with cellpose
>>>ERROR<<<
Traceback (most recent call last):
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 429, in run_s2p
>>>ERROR<<<
    op = run_plane(op, ops_path=ops_path)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 292, in run_plane
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 131, in pipeline
>>>ERROR<<<
    classfile=classfile)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 112, in detection_wrapper
>>>ERROR<<<
    diameter=ops.get('diameter', None))
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\anatomical.py", line 184, in select_rois
    pretrained_model=ops['pretrained_model'])
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\suite2p\detection\anatomical.py", line 100, in roi_detect
>>>ERROR<<<
    cellprob_threshold=cellprob_threshold, flow_threshold=flow_threshold)[0]
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\models.py", line 567, in eval
>>>ERROR<<<
    stitch_threshold=stitch_threshold,
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\models.py", line 653, in _run_cp
    use_gpu=self.gpu, device=self.device)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\dynamics.py", line 725, in compute_masks
>>>ERROR<<<
    mask = remove_bad_flow_masks(mask, dP, threshold=flow_threshold, use_gpu=use_gpu, device=device)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\dynamics.py", line 580, in remove_bad_flow_masks
>>>ERROR<<<
    merrors, _ = metrics.flow_error(masks, flows, use_gpu, device)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\metrics.py", line 282, in flow_error
>>>ERROR<<<
    dP_masks = dynamics.masks_to_flows(maski, use_gpu=use_gpu, device=device)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\dynamics.py", line 277, in masks_to_flows
>>>ERROR<<<
    mu, mu_c = masks_to_flows_device(masks, device=device)
  File "c:\users\sara.desktop-tsb8h9c\anaconda3\envs\suite2p\lib\site-packages\cellpose\dynamics.py", line 212, in masks_to_flows_cpu
>>>ERROR<<<
    T = _extend_centers(T, y, x, ymed, xmed, np.int32(lx), np.int32(niter))
TypeError: expected dtype object, got 'numpy.dtype[float64]'
Interrupted by error (not finished)
```

**Comment by carsen-stringer** [comment]
can you please try `pip install numba --upgrade`?

you could also try making a clean environment and reinstalling

**Comment by carsen-stringer** [comment]
if this doesn't work for you I'll reopen the issue
