### ISSUE TITLE
filenofounderrors

### ISSUE THREAD

**Issue by mpr121** [MouseLand/suite2p#855]
I setup the ops parameters and run suite2p. The app returned the following errors. I ran it in Win11 home edition, suite2p 0.11.0.  Look like at the end of error message, the error might be related to the wrong format for a directory. The program used "\\\\" instead of "\\\" ?  could you advise how to fix the errors? thank you very much!

Below are the error messages:

{'data_path': ['H:\\M159_group1_24weeks\\OO'], 'subfolders': [], 'h5py_key': 'data', 'save_path0': 'H:\\M159_group1_24weeks\\OO_processed', 'fast_disk': 'c:\\temp_storage', 'input_format': 'tif'}
NOTE: nplanes 4 nrois 3 => ops['nplanes'] = 12
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 390, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 281, in mesoscan_to_binary
    ops1, fs, reg_file, reg_file_chan2 = utils.find_files_open_binaries(ops1, False)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\utils.py", line 190, in find_files_open_binaries
>>>ERROR<<<
    reg_file.append(open(ops['reg_file'], 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\temp_storage\\suite2p\\plane0\\data.bin'
Interrupted by error (not finished)
{'data_path': ['H:\\M159_group1_24weeks\\OO'], 'subfolders': [], 'h5py_key': 'data', 'save_path0': 'H:\\M159_group1_24weeks\\OO_processed', 'fast_disk': 'c:\\temp_storage', 'input_format': 'tif'}
NOTE: nplanes 4 nrois 3 => ops['nplanes'] = 12
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
>>>ERROR<<<
    main()
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
>>>ERROR<<<
    run_s2p(ops, db)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 390, in run_s2p
>>>ERROR<<<
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tiff.py", line 281, in mesoscan_to_binary
>>>ERROR<<<
    ops1, fs, reg_file, reg_file_chan2 = utils.find_files_open_binaries(ops1, False)
  File "C:\Users\myye1\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\utils.py", line 190, in find_files_open_binaries
    reg_file.append(open(ops['reg_file'], 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\\\temp_storage\\\\suite2p\\\\plane0\\\\data.bin'
Interrupted by error (not finished)

**Comment by tbabola** [comment]
Could be totally off base here, but your temp_storeage path is c:\\, whereas above it is capital C:\\. 

The double-slashes in the path name are expected on Windows.

**Comment by mpr121** [comment]
I found out that it is a bug in the utils.py file. The fixed the error, at around line 290,
     if not os.path.isdir(ops['fast_disk']):
should be changed to :  
    if not os.path.isdir(fast_disk):

**Comment by willyh101** [comment]
> I found out that it is a bug in the utils.py file for the suite2p 0.11.0 version. at around line 290 in the file, if not os.path.isdir(ops['fast_disk']): os.makedirs(ops['fast_disk']) should be changed to : if not os.path.isdir(fast_disk): os.makedirs(fast_disk)

I can confirm this fixes it for me too.

**Comment by chriski777** [comment]
Thanks, @willyh101 and @mpr121! This fix has been merged.
