### ISSUE TITLE
Registration error with h5 files

### ISSUE THREAD

**Issue by GergelyTuri** [MouseLand/suite2p#870]
Hi, 
I try to register h5 files with the latest version of Suite2p (0.11.1) and getting the following error: 

```
>>>>> started run at 29/08/2022 09:29:54{'data_path': ['/data2/gergely/invivo_DATA/sleep/2aCre08a_4/9_17_SD/TSeries-09172021-SD-001'], 'subfolders': [], 'h5py_key': 'imaging', 'save_path0': '/data2/gergely/invivo_DATA/sleep/2aCre08a_4/9_17_SD/TSeries-09172021-SD-001/TSeries-09172021-SD-001_Cycle00001_Element00001.sima', 'fast_disk': '/scratch/suite2p_working', 'input_format': 'h5'}
h5
** Found 1 h5 files - converting to binary **
NOTE: using a list of h5 files:
['/data2/gergely/invivo_DATA/sleep/2aCre08a_4/9_17_SD/TSeries-09172021-SD-001/TSeries-09172021-SD-001_Cycle00001_Element00001.h5']
time 1.36 sec. Wrote 128000 frames per binary for 2 planes
>>>>>>>>>>>>>>>>>>>>> PLANE 0 <<<<<<<<<<<<<<<<<<<<<<
NOTE: not registered / registration forced with ops['do_registration']>1
      (no previous offsets to delete)
NOTE: applying default /home/gergely/.suite2p/classifiers/classifier_user.npy
----------- REGISTRATION
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/run_s2p.py", line 429, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/run_s2p.py", line 292, in run_plane
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/run_s2p.py", line 78, in pipeline
    registration_outputs = registration.register.registration_wrapper(f_reg, f_raw=f_raw, f_reg_chan2=f_reg_chan2, f_raw_chan2=f_raw_chan2, 
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/registration/register.py", line 612, in registration_wrapper
    outputs = compute_reference_and_register_frames(f_align_in, f_align_out=f_align_out, refImg=refImg, ops=ops)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/registration/register.py", line 385, in compute_reference_and_register_frames
    refImg = compute_reference(frames, ops=ops)
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/registration/register.py", line 133, in compute_reference
    ymax, xmax, cmax = rigid.phasecorr(
  File "/home/gergely/anaconda3/envs/suite2p_latest/lib/python3.8/site-packages/suite2p/registration/rigid.py", line 104, in phasecorr
    ymax[t], xmax[t] = np.unravel_index(np.argmax(cc[t], axis=None), (2 * lcorr + 1, 2 * lcorr + 1))
  File "<__array_function__ internals>", line 5, in unravel_index
>>>ERROR<<<
ValueError: index 666 is out of bounds for array with size 1
```

The settings in the ops and db file are the default except for the pointers to the data, fast disk and output path. This one ☝️ is a two-plane dataset, but i have the same issue when trying to register one plane data (well, the index in the `ValueError` is different). I was able to register these datasets with earlier versions of suite2p. Any suggestions?

**Comment by chriski777** [comment]
Hi @GergelyTuri, thanks for letting us know about this issue. Just wondering, when you try to register one plane data you mentioned that the index for the ValueError you get is different. Does the error still say it is out of bounds for array with size 1? Also, since you're working with h5 input files, have you tried running suite2p after changing just the `h5py` and the `h5py_key` parameters in the `ops` settings instead of the `data_path` and `fast_disk` parameters as you mentioned?

**Comment by GergelyTuri** [comment]
Hi Chris, 
Yes, the `array with size 1` is the same regardless of the number of planes, only the index value changes (816 and 892, 1 plane vs. 3 planes). I guess, i did not mention that although I use the default settings, but these are the default settings called by the built in `dendrites/axons` example ops. Sorry about that. 
I use the GUI to run my datasets and the `h5_key` is set to the custom key I have in my h5 files.

**Comment by chriski777** [comment]
Gotcha, have you tried running it without the GUI (e.g., Google CoLab or Jupyter notebook on a local machine)? Could you also update your suite2p to work off this [branch](https://github.com/MouseLand/suite2p/tree/refactor)?

**Comment by chriski777** [comment]
@GergelyTuri, are you still running into this issue?

**Comment by GergelyTuri** [comment]
Hi Chris, I was preoccupied with a few things, let me try this week.

From: Chris Ki ***@***.***>
Sent: Saturday, October 15, 2022 10:57 PM
To: MouseLand/suite2p ***@***.***>
Cc: Turi, Gergely ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [MouseLand/suite2p] Registration error with h5 files (Issue #870)


@GergelyTuri<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGergelyTuri&data=05%7C01%7Cgt2253%40cumc.columbia.edu%7C9b8b3d366ef84f1b48f708daaf222712%7Cb0002a9b0017404d97dc3d3bab09be81%7C1%7C0%7C638014858478957968%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7G9R55bc%2BCXIC6zjXwDIUskm7C0ZDDL9tAL9BbENQRU%3D&reserved=0>, are you still running into this issue?

-

**Comment by chriski777** [comment]
Hi @GergelyTuri, just checking in again, is this error still present?

**Comment by GergelyTuri** [comment]
Hey @chriski777 , 
i built s2p from that branch you suggested and ran a dataset. Here is the trace: 
```
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/gergely/anaconda3/envs/s2p-tester/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gergely/anaconda3/envs/s2p-tester/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gergely/code/s2p_temp/suite2p/suite2p/__main__.py", line 78, in <module>
    main()
  File "/home/gergely/code/s2p_temp/suite2p/suite2p/__main__.py", line 71, in main
    run_s2p(ops, db)
  File "/home/gergely/code/s2p_temp/suite2p/suite2p/run_s2p.py", line 404, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "/home/gergely/code/s2p_temp/suite2p/suite2p/io/h5.py", line 69, in h5py_to_binary
    im = f[key][irange,...]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
>>>ERROR<<<
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/gergely/anaconda3/envs/s2p-tester/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 814, in __getitem__
    selection = sel.select(self.shape, args, dataset=self)
  File "/home/gergely/anaconda3/envs/s2p-tester/lib/python3.8/site-packages/h5py/_hl/selections.py", line 82, in select
    return selector.make_selection(args)
  File "h5py/_selector.pyx", line 276, in h5py._selector.Selector.make_selection
  File "h5py/_selector.pyx", line 187, in h5py._selector.Selector.apply_args
TypeError: Indexing arrays must have integer dtypes
Interrupted by error (not finished)
```

**Comment by GergelyTuri** [comment]
i also want to add, that this dataset was successfully processed earlier w/ version 0.7.0

**Comment by chriski777** [comment]
I see. Could you include a dropbox link to the dataset you used along with a copy of the `ops` file you used?

**Comment by carsen-stringer** [comment]
closing due to inactivity
