### ISSUE TITLE
Shape mismatch error

### ISSUE THREAD

**Issue by Andrew-ell** [MouseLand/suite2p#876]
Hi! I've been encountering the following error when running suite2p:

```
----------- SPIKE DECONVOLUTION
----------- Total 0.16 sec.
Plane 1 processed in 216.69 sec (can open in GUI).
total = 469.15 sec.
Creating combined view
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 438, in run_s2p
    io.combined(save_folder, save=True)
  File "C:\Users\Analysiscomputer\anaconda3\envs\suite2p\lib\site-packages\suite2p\io\save.py", line 106, in combined
    meanImgE[np.ix_(yrange, xrange)] = ops['meanImgE']
ValueError: shape mismatch: value array of shape (1028,1024) could not be broadcast to indexing result of shape (512,512)
Interrupted by error (not finished)
```

This error persists when running stacked OME-tiffs (7.34 GB file) and with the images in separate files. I have tried reinstalling suite2p but I encounter the same error. Do you have any suggestions?

**Comment by chriski777** [comment]
Hey @Andrew-ell, thanks for letting us know about this issue. It's a bit difficult for us to replicate this issue on our side. Do you think it would be possible to include a link to download the files that are causing this issue?

**Comment by Andrew-ell** [comment]
Thank you; I have shared the file at https://www.dropbox.com/s/ek528gcsicjql2d/M28.tiff?dl=0

**Comment by chriski777** [comment]
Hey @Andrew-ell, sorry, but the link expired. Could you upload the data again? Thanks!

**Comment by Andrew-ell** [comment]
It is now linked at https://www.dropbox.com/s/ylgai9t6h208bfc/M28.tiff?dl=0

Thanks!

**Comment by chriski777** [comment]
Hi @Andrew-ell, sorry for the late reply! Can you elaborate on what settings you had in your `ops.npy` file? I've tried running suite2p with the default settings on this data file and it seems to run fine on my end... It would be great if you could just send this file (if you can)!

**Comment by chriski777** [comment]
Hi @Andrew-ell, I'll be closing this issue now due to inactivity. Feel free to reopen it if the issue persists with the latest version of suite2p!
