### ISSUE TITLE
error: 'local variable 'reg_file' referenced before assignment'

### ISSUE THREAD

**Issue by vrutten** [MouseLand/suite2p#88]
Hi,

Thanks a lot for this great tool.
Everything was working smoothly until I upgraded the package today using `pip install suite2p --upgrade`. (I'm not sure if this is indeed the source of the problem)

When I now try to run suite2p on simple single plane .tiff data [T,Y,X], I get the following error:

>>>Found 2 tifs
time 31.2616. Wrote tifs to binaries for 1 planes
===== 2018.09.08 13:09:39 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>>>ERROR<<<
    "__main__", mod_spec)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/__main__.py", line 32, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/run_s2p.py", line 137, in run_s2p
    ops1 = register.register_binary(ops1) # register tiff
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/register.py", line 192, in register_binary
    op = register_binary(op)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/register.py", line 197, in register_binary
    refImg = pick_init(ops)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/register.py", line 345, in pick_init
    frames = subsample_frames(ops, nFramesInit)
  File "/groups/ahrens/home/ruttenv/anaconda3/lib/python3.6/site-packages/suite2p/register.py", line 301, in subsample_frames
    reg_file.seek(nbytesread * istart[j], 0)
>>>ERROR<<<
UnboundLocalError: local variable 'reg_file' referenced before assignment
Interrupted by error (not finished)

In case it is useful, here is an image capturing the settings:
![screen shot 2018-09-08 at 1 50 48 pm](https://user-images.githubusercontent.com/15912669/45257080-46c6ac80-b36e-11e8-9d62-2a40d2b36363.png)

I've also tried running it on a dataset which I had already 'suite2p-ed' successfully (new verb? ^^) and got the same error message.

Thanks for any help!

**Comment by marius10p** [comment]
Do you know which version this is? We just fixed something, try upgrading again?

**Comment by vrutten** [comment]
great - just re-upgraded now and it's all fixed - thanks for the quick response!
