### ISSUE TITLE
error using sbx files (converting sbx to binary)

### ISSUE THREAD

**Issue by s-j-k** [MouseLand/suite2p#882]
Hello,

I was previously able to use sbx files directly in the suite2p GUI. However when I try to do it recently, I receive the errors below. This also happens on my colleague's computer. I have updated suite2p but the problem persists.

Thank you in advance,
Su
`
** Found 1 sbx - converting to binary **
Scanbox files:
C:/Users/sjkim1/Desktop/scratch/sk70\sk70_036_001.sbx
Removing 76 dead columns while loading sbx data.
Removing 0 dead rows while loading sbx data.
>>>ERROR<<<
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
>>>ERROR<<<
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 390, in run_s2p
    ops0 = convert_funs[ops['input_format']](ops.copy())
  File "C:\ProgramData\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\sbx.py", line 97, in sbx_to_binary
    ops1[j]['meanImg'] = np.zeros((im.shape[3],im.shape[4]),np.float32)
IndexError: list index out of range
Interrupted by error (not finished)
`

**Comment by carsen-stringer** [comment]
can you please report the version which worked vs which failed? going to close for now, but please reopen if you haven't been able to fix this
