### ISSUE TITLE
Error during ROI detection, valueerror: cannot compute length

### ISSUE THREAD

**Issue by cgaletzka** [MouseLand/suite2p#887]
Hi,

Thank you for providing this great software. I am running suite2p on consecutive widefield imaging .tif files. I just updated suite2p to 0.11.1 and am receiving an error message during ROI detection. Already tried to run suite2p from a clean conda environment with the newest github version but the same error happens. However, when rigid registration is performed, suite2p does the ROI detection without error. Could you please let me know how to fix this error?

{'data_path': ['F:/WT_vs_HUM/Cage_6/20220927_D01/E220907-1-X/rigid'], 'subfolders': [], 'save_path0': 'F:/WT_vs_HUM/Cage_6/20220927_D01/E220907-1-X/rigid', 'fast_disk': 'F:/WT_vs_HUM/Cage_6/20220927_D01/E220907-1-X/rigid', 'input_format': 'tif'}
tif
** Found 76 tifs - converting to binary **
800 frames of binary, time 4.90 sec.
1600 frames of binary, time 9.13 sec.
2400 frames of binary, time 13.65 sec.
time 552.51 sec. Wrote 96180 frames per binary for 1 planes
PLANE 0
NOTE: not running registration, ops['do_registration']=0
binary path: F:/WT_vs_HUM/Cage_6/20220927_D01/E220907-1-X/rigid\suite2p\plane0\data.bin
NOTE: applying default C:\Users\cedri\.suite2p\classifiers\classifier_user.npy
ROI DETECTION
Binning movie in chunks of length 42
ERROR
Traceback (most recent call last):
  File "C:\Users\cedri\.conda\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
ERROR
    return _run_code(code, main_globals, None,
  File "C:\Users\cedri\.conda\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
ERROR
    main()
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 71, in main
    run_s2p(ops, db)
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 429, in run_s2p
    op = run_plane(op, ops_path=ops_path)
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 292, in run_plane
    ops = pipeline(f_reg, f_raw, f_reg_chan2, f_raw_chan2, run_registration, ops, stat=stat)
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\run_s2p.py", line 129, in pipeline
    ops, stat = detection.detection_wrapper(f_reg,
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 112, in detection_wrapper
    mov = bin_movie(f_reg, bin_size, yrange=yrange, 
  File "C:\Users\cedri\.conda\envs\suite2p\lib\site-packages\suite2p\detection\detect.py", line 42, in bin_movie
    for k in np.arange(0, n_frames, batch_size):
ValueError: arange: cannot compute length
Interrupted by error (not finished)

Here are my settings:

<img width="614" alt="suite2p_settings" src="https://user-images.githubusercontent.com/57383165/193489514-0900249e-64c8-420f-9324-4a232fa3ee1e.png">

Only the data_raw.bin is saved:

<img width="663" alt="data not saved" src="https://user-images.githubusercontent.com/57383165/193489814-e163d580-5a26-4780-8cb5-0a0d1203a302.png">

**Comment by cgaletzka** [comment]
This error message does not show up when the option 'keep_movie_raw' is unchecked.
