### ISSUE TITLE
Error in manual labeling in 2 channel analysis

### ISSUE THREAD

**Issue by faezehrabbani97** [MouseLand/suite2p#904]
Hi
I want to use manual labeling for data of 2 channel analysis but it gives me this error:

Traceback (most recent call last):
  File "C:\Users\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 415, in proc_ROI
    F, Fneu, F_chan2, Fneu_chan2, spks, ops, stat = masks_and_traces(self.parent.ops, stat0, self.parent.stat)
  File "C:\Users\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 48, in masks_and_traces
    F, Fneu, F_chan2, Fneu_chan2 = extract_traces_from_masks(ops,
  File "C:\Users\Anaconda3\envs\suite2p\lib\site-packages\suite2p\extraction\extract.py", line 135, in extract_traces_from_masks
    F_chan2, Fneu_chan2 = extract_traces(cell_masks, neuropil_masks, batch_size=batch_size)
TypeError: extract_traces() missing 1 required positional argument: 'neuropil_masks'

I don't face the same problem when I want to use "manual labeling" for 1 channel data.
I already have the last version of suite2p and I am using python 3.8 on windows

**Comment by chriski777** [comment]
Hi @faezehrabbani97, thanks for letting us know about this. This has been fixed and will be included in an updated release. If you'd like to use the updated version, feel free to pull the latest version of the code on the refactor branch!
