### ISSUE TITLE
ROI merge not working

### ISSUE THREAD

**Issue by yz22015** [MouseLand/suite2p#926]
### Describe the issue:

Hi,

I want to merge a split ROI in suite2p GUI with key board shortcut `Alt + Enter`. The ROIs remained split and there was an error message:

### Reproduce the code example:

```python
Bug with GUI.
```

### Error message:

```shell
merging activity... this may take some time
Traceback (most recent call last):
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\gui\gui2p.py", line 303, in keyPressEvent
    merge.do_merge(self)
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\gui\merge.py", line 32, in do_merge
    merge_activity_masks(parent)
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\gui\merge.py", line 150, in merge_activity_masks
    parent.stat = roi_stats(parent.stat, d0[0], d0[1], parent.Ly, parent.Lx)
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\detection\stats.py", line 220, in roi_stats
    n_overlaps = ROI.get_overlap_count_image(rois=rois, Ly=Ly, Lx=Lx)
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\detection\stats.py", line 98, in get_overlap_count_image
    return count_overlaps(Ly=Ly, Lx=Lx, ypixs=[roi.ypix for roi in rois], xpixs=[roi.xpix for roi in rois])
  File "C:\Users\x\Anaconda3\envs\suite2p_v0_11_0\lib\site-packages\suite2p\detection\stats.py", line 309, in count_overlaps
    overlap[ypix, xpix] += 1
IndexError: index 162 is out of bounds for axis 1 with size 10
```

### Version information:

suite2p v0.11.0

### Context for the issue:

I see that merge issues have been reported in issue #860

**Comment by carsen-stringer** [comment]
I cannot reproduce this, please update to the latest version, `pip install suite2p --upgrade`
