### ISSUE TITLE
BUG: error when saving ops file in gui

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#934]
### Describe the issue:

Hi
I get an error (see below) when I try to save the ops file in the GUI.
Thanks
Adam

### Reproduce the code example:

```python
in gui
```

### Error message:

```shell
Traceback (most recent call last):
  File "/home/adamranson/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/rungui.py", line 459, in save_ops
    self.save_text()
  File "/home/adamranson/miniconda3/envs/suite2p/lib/python3.8/site-packages/suite2p/gui/rungui.py", line 484, in save_text
    self.ops[key] = self.editlist[k].get_text(self.intkeys, self.boolkeys)
TypeError: get_text() missing 1 required positional argument: 'stringkeys'
```

### Version information:

suite2p v0.12.0

**Comment by chriski777** [comment]
Hi @ransona, thanks for reporting this. The new release should contain the fix for this. Please feel free to reopen this if the error still persists.
