### ISSUE TITLE
BUG: <not able to run the suite2p GUI: with type error>

### ISSUE THREAD

**Issue by gistempert** [MouseLand/suite2p#942]
### Describe the issue:

I'm not able to run the suite2p GUI: with type error>

### Reproduce the code example:

```python
(In Powershell Prompt)
conda activiate suite2p
suite2p
```

### Version information:

Traceback (most recent call last):
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\~\Anaconda3\envs\suite2p\Scripts\suite2p.exe\__main__.py", line 7, in <module>
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 74, in main
    gui.run()
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 718, in run
    GUI = MainWindow(statfile=statfile)
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 87, in __init__
    b0 = self.make_buttons()
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 146, in make_buttons
    masks.make_colorbar(self, b0)
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 191, in make_colorbar
    colorbarW = pg.GraphicsLayoutWidget(parent)
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsLayoutWidget.py", line 51, in __init__
    GraphicsView.__init__(self, parent)
  File "C:\Users\~\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 61, in __init__
    QtWidgets.QGraphicsView.__init__(self, parent)
TypeError: 'PySide6.QtWidgets.QGraphicsView.__init__' called with wrong argument types: PySide6.QtWidgets.QGraphicsView.__init__(MainWindow) Supported signatures: PySide6.QtWidgets.QGraphicsView.__init__(Union[PySide6.QtWidgets.QWidget, NoneType] = None) PySide6.QtWidgets.QGraphicsView.__init__(PySide6.QtWidgets.QGraphicsScene, Union[PySide6.QtWidgets.QWidget, NoneType] = None)

**Comment by j9ac9k** [comment]
This is a pyqtgraph issue and an incompatibility with pyside6 6.5.  We (pyqtgraph maintainers) are about to release PyQtGraph 0.13.3 which will address this issue.

**Comment by chriski777** [comment]
@gistempert, based on what @j9ac9k said above, we suggest you update pyQyGraph to 0.13.3 to solve this issue. Please feel free to reopen this issue if the issue persists!
