### ISSUE TITLE
issue with Qt setting DPI awareness info

### ISSUE THREAD

**Issue by apostolideslab** [MouseLand/suite2p#947]
### Describe the issue:

Dear all,

I just reinstalled Suite2p due to some issues and now I'm getting a strange error I haven't seen before. Unfortunately, solving the issue appears beyond my troubleshooting capabilities and so I'm reaching out here if anyone's encountered similar (and how to solve it). Here is the terminal response after I try running suite2p

(suite2p) PS C:\Users\Pierre> python -m suite2p
qt.qpa.window: SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2) failed: COM error 0x5: Access is denied.
Qt's default DPI awareness context is DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2. If you know what you are doing you can overwrite this default using qt.conf (https://doc.qt.io/qt-6/highdpi.html#configuring-windows)
Traceback (most recent call last):
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 78, in <module>
    main()
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__main__.py", line 74, in main
    gui.run()
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 718, in run
    GUI = MainWindow(statfile=statfile)
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 87, in __init__
    b0 = self.make_buttons()
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\gui2p.py", line 146, in make_buttons
    masks.make_colorbar(self, b0)
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\masks.py", line 191, in make_colorbar
    colorbarW = pg.GraphicsLayoutWidget(parent)
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsLayoutWidget.py", line 51, in __init__
    GraphicsView.__init__(self, parent)
  File "C:\Users\Pierre\Anaconda3\envs\suite2p\lib\site-packages\pyqtgraph\widgets\GraphicsView.py", line 61, in __init__
    QtWidgets.QGraphicsView.__init__(self, parent)
TypeError: arguments did not match any overloaded call:
  QGraphicsView(parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MainWindow'
  QGraphicsView(scene: QGraphicsScene, parent: typing.Optional[QWidget] = None): argument 1 has unexpected type 'MainWindow'

From my understanding, the Qt package is simply trying to set the DPI resolution awareness and there's an issue with the permissions. However, from my understanding my account has admin privileges (and I get the same issue when running anaconda prompt as admin) and I'm unclear what other settings might need changing here.

Any insight would be extremely helpful! Thank you so much!

### Provide environment info:

active environment : suite2p
    active env location : C:\Users\Pierre\Anaconda3\envs\suite2p
            shell level : 2
       user config file : C:\Users\Pierre\.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.7=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Pierre\Anaconda3  (writable)
      conda av data dir : C:\Users\Pierre\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Pierre\Anaconda3\pkgs
                          C:\Users\Pierre\.conda\pkgs
                          C:\Users\Pierre\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Pierre\Anaconda3\envs
                          C:\Users\Pierre\.conda\envs
                          C:\Users\Pierre\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

**Comment by roshea101** [comment]
Hi,

I am having this same error persist after multiple re-installs. Does anyone have an explanation?

**Comment by carsen-stringer** [comment]
Are you using python 3.8?

**Comment by roshea101** [comment]
I was just able to install on another Windows 10 machine without generating this error, so this could just be a machine-specific issue

**Comment by carsen-stringer** [comment]
please try the latest suite2p version `pip install suite2p==0.99rc` and reopen the issue if the behavior is replicated in the new version
