### ISSUE TITLE
BUG: Error with extracting manually drawn ROIs in multiplane/combined image file

### ISSUE THREAD

**Issue by pbokiniec** [MouseLand/suite2p#952]
### Describe the issue:

Hey there,

I have run into a problem that I'm not sure the solution to.

I am trying to manually draw ROIs and extract their traces from an imaging dataset. This works smoothly when i load single plane images into suite2p. However, when i upload multiplane images (combined stats.npy), I am able to draw ROIs, however run into the following error. This is irrespective of whether I try to extract a single drawn ROI or multiple drawn ones. Moreover, this also happens if i have 2 or 5 different frames in my imaging sequence.

Previously i was using an old instance of suite2p (ver 11.1) and upgraded to the latest instance (ver 12.1), however this did not resolve the issue.

Any and all help is greatly appreciated.

Cheers!
Phill

### Reproduce the code example:

```python
time to draw and plot masks:  0.8361 sec
1 cells added to manual GUI
Masks made in 3.90 sec.
Extracted fluorescence from 1 ROIs in 0 frames, 0.00 sec.
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 421, in proc_ROI
    self.plot_trace()
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 438, in plot_trace
    fmax = f.max()
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\numpy\core\_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

### Error message:

```shell
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 421, in proc_ROI
    self.plot_trace()
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\suite2p\gui\drawroi.py", line 438, in plot_trace
    fmax = f.max()
  File "C:\Users\user\Anaconda3\envs\suite2p\lib\site-packages\numpy\core\_methods.py", line 40, in _amax
    return umr_maximum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation maximum which has no identity
```

### Version information:

11.1 and 12.1

**Comment by carsen-stringer** [comment]
you cannot draw manual ROIs in combined view
